/** Built-in Terminal REST templates seeded per owner (RouterOS 7.1+ REST paths). */
export type TerminalBuiltinTemplate = {
  name: string;
  description: string;
  category: string;
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  path: string;
  body: string | null;
};

export const TERMINAL_BUILTIN_TEMPLATES: TerminalBuiltinTemplate[] = [
  // system
  {
    name: "System resource",
    description: "CPU, memory, uptime and RouterOS version",
    category: "system",
    method: "GET",
    path: "/system/resource",
    body: null,
  },
  {
    name: "Identity",
    description: "Router identity/name",
    category: "system",
    method: "GET",
    path: "/system/identity",
    body: null,
  },
  {
    name: "System health",
    description: "Board temperature and health sensors",
    category: "system",
    method: "GET",
    path: "/system/health",
    body: null,
  },
  {
    name: "RouterBoard",
    description: "Model, serial number and board type",
    category: "system",
    method: "GET",
    path: "/system/routerboard",
    body: null,
  },
  {
    name: "System clock",
    description: "Current router date and time",
    category: "system",
    method: "GET",
    path: "/system/clock",
    body: null,
  },
  {
    name: "Installed packages",
    description: "RouterOS packages and versions",
    category: "system",
    method: "GET",
    path: "/system/package",
    body: null,
  },
  {
    name: "Reboot router",
    description: "Reboot the RouterBoard immediately",
    category: "system",
    method: "POST",
    path: "/system/reboot",
    body: null,
  },
  // security
  {
    name: "IP services",
    description: "List enabled admin services (www, ssh, api...)",
    category: "security",
    method: "GET",
    path: "/ip/service",
    body: null,
  },
  {
    name: "Firewall filter",
    description: "List firewall filter rules",
    category: "security",
    method: "GET",
    path: "/ip/firewall/filter",
    body: null,
  },
  {
    name: "Firewall NAT",
    description: "List firewall NAT rules",
    category: "security",
    method: "GET",
    path: "/ip/firewall/nat",
    body: null,
  },
  {
    name: "Address list",
    description: "List firewall address-lists",
    category: "security",
    method: "GET",
    path: "/ip/firewall/address-list",
    body: null,
  },
  {
    name: "Active connections",
    description: "Current firewall/NAT connection tracking entries",
    category: "security",
    method: "GET",
    path: "/ip/firewall/connection",
    body: null,
  },
  // hotspot
  {
    name: "Hotspot servers",
    description: "Configured hotspot service instances",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot",
    body: null,
  },
  {
    name: "Hotspot active",
    description: "Currently connected hotspot users",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/active",
    body: null,
  },
  {
    name: "Hotspot users",
    description: "Registered hotspot users / vouchers",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/user",
    body: null,
  },
  {
    name: "Hotspot hosts",
    description: "Hosts seen by hotspot service",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/host",
    body: null,
  },
  {
    name: "IP bindings",
    description: "Hotspot IP bindings (bypass/blocked)",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/ip-binding",
    body: null,
  },
  {
    name: "Hotspot profiles",
    description: "Server-side hotspot profiles",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/profile",
    body: null,
  },
  {
    name: "User profiles",
    description: "Bandwidth and time limits for hotspot users",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/user/profile",
    body: null,
  },
  {
    name: "Walled garden",
    description: "Destinations reachable before hotspot login",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/walled-garden",
    body: null,
  },
  {
    name: "Hotspot cookies",
    description: "Remember-me hotspot sessions",
    category: "hotspot",
    method: "GET",
    path: "/ip/hotspot/cookie",
    body: null,
  },
  {
    name: "Create hotspot user",
    description: "Add a voucher user — edit name/password before Send",
    category: "hotspot",
    method: "POST",
    path: "/ip/hotspot/user",
    body: '{"name":"voucher1","password":"changeme","profile":"default","comment":"Created from Terminal"}',
  },
  {
    name: "Block MAC address",
    description: "Block a device by MAC via hotspot IP binding",
    category: "hotspot",
    method: "POST",
    path: "/ip/hotspot/ip-binding",
    body: '{"mac-address":"AA:BB:CC:DD:EE:FF","type":"blocked","comment":"Blocked from Terminal"}',
  },
  // network
  {
    name: "Interfaces",
    description: "All interfaces with traffic counters",
    category: "network",
    method: "GET",
    path: "/interface",
    body: null,
  },
  {
    name: "IP addresses",
    description: "IPv4/IPv6 addresses assigned to interfaces",
    category: "network",
    method: "GET",
    path: "/ip/address",
    body: null,
  },
  {
    name: "DNS settings",
    description: "DNS servers and cache settings",
    category: "network",
    method: "GET",
    path: "/ip/dns",
    body: null,
  },
  {
    name: "IP pools",
    description: "Hotspot and DHCP address pools",
    category: "network",
    method: "GET",
    path: "/ip/pool",
    body: null,
  },
  {
    name: "Pool usage",
    description: "Addresses currently leased from pools",
    category: "network",
    method: "GET",
    path: "/ip/pool/used",
    body: null,
  },
  {
    name: "Cloud DDNS",
    description: "MikroTik cloud / DDNS status",
    category: "network",
    method: "GET",
    path: "/ip/cloud",
    body: null,
  },
  {
    name: "WireGuard peers",
    description: "WireGuard VPN peers (Magic Cloud hub, etc.)",
    category: "network",
    method: "GET",
    path: "/interface/wireguard/peers",
    body: null,
  },
  {
    name: "DHCP leases",
    description: "Active DHCP leases",
    category: "network",
    method: "GET",
    path: "/ip/dhcp-server/lease",
    body: null,
  },
  {
    name: "ARP table",
    description: "ARP entries",
    category: "network",
    method: "GET",
    path: "/ip/arp",
    body: null,
  },
  {
    name: "Routes",
    description: "Routing table",
    category: "network",
    method: "GET",
    path: "/ip/route",
    body: null,
  },
  // qos
  {
    name: "Queue tree",
    description: "Simple queues and queue tree rules",
    category: "qos",
    method: "GET",
    path: "/queue/tree",
    body: null,
  },
  // diagnostics
  {
    name: "Ping 1.1.1.1",
    description: "Send 4 ICMP pings to Cloudflare DNS",
    category: "diagnostics",
    method: "POST",
    path: "/ping",
    body: '{"address":"1.1.1.1","count":"4"}',
  },
  {
    name: "Ping 8.8.8.8",
    description: "Send 4 ICMP pings to Google DNS",
    category: "diagnostics",
    method: "POST",
    path: "/ping",
    body: '{"address":"8.8.8.8","count":"4"}',
  },
  {
    name: "DNS resolve",
    description: "Resolve a hostname via the router DNS",
    category: "diagnostics",
    method: "POST",
    path: "/resolve",
    body: '{"address":"google.com","type":"A"}',
  },
  {
    name: "Traceroute 8.8.8.8",
    description: "Trace route to Google DNS",
    category: "diagnostics",
    method: "POST",
    path: "/tool/traceroute",
    body: '{"address":"8.8.8.8","count":"1"}',
  },
  {
    name: "Torch WAN",
    description: "Live traffic snapshot on ether1 (2s)",
    category: "diagnostics",
    method: "POST",
    path: "/tool/torch",
    body: '{"interface":"ether1","duration":"2s"}',
  },
  {
    name: "Bandwidth test TCP",
    description: "5s TCP bandwidth test to Cloudflare",
    category: "diagnostics",
    method: "POST",
    path: "/tool/bandwidth-test",
    body: '{"address":"1.1.1.1","protocol":"tcp","duration":"5s"}',
  },
  {
    name: "Logs (last 50)",
    description: "Recent system logs",
    category: "diagnostics",
    method: "GET",
    path: "/log",
    body: null,
  },
  // backup
  {
    name: "List files",
    description: "Files on the router (.backup, scripts, etc.)",
    category: "backup",
    method: "GET",
    path: "/file",
    body: null,
  },
  {
    name: "Backup config",
    description: "Create a full system backup",
    category: "backup",
    method: "POST",
    path: "/system/backup/save",
    body: '{"name":"magic-backup"}',
  },
];

/** Templates added after the original 2026-07-24 seed (for migration backfill). */
export const TERMINAL_NEW_BUILTIN_NAMES = new Set([
  "System health",
  "RouterBoard",
  "System clock",
  "Installed packages",
  "Active connections",
  "Hotspot servers",
  "Hotspot profiles",
  "User profiles",
  "Walled garden",
  "Hotspot cookies",
  "Create hotspot user",
  "Block MAC address",
  "IP addresses",
  "DNS settings",
  "IP pools",
  "Pool usage",
  "Cloud DDNS",
  "WireGuard peers",
  "Queue tree",
  "DNS resolve",
  "Traceroute 8.8.8.8",
  "Bandwidth test TCP",
  "List files",
]);
