// Generated by `bun run i18n:audit`. Do not edit by hand.
import type { I18nReport } from "./report-types";

export const i18nReport: I18nReport = {
  "generatedAt": "2026-09-08T02:38:34.231Z",
  "sourceHash": "2346a12e14101d3a",
  "sourceCounts": {
    "ui": 256,
    "copy": 237,
    "action": 2
  },
  "languages": {
    "zh": {
      "total": 493,
      "translated": 493,
      "coverage": 100,
      "missing": [],
      "todo": [],
      "wrongScript": [],
      "unused": [
        {
          "ns": "ui",
          "key": "Magic Dude"
        },
        {
          "ns": "ui",
          "key": "Trial Guest Access"
        },
        {
          "ns": "ui",
          "key": "Fair Share QoS"
        },
        {
          "ns": "ui",
          "key": "Auto Daily Backup"
        },
        {
          "ns": "ui",
          "key": "Hotspot Operations"
        },
        {
          "ns": "ui",
          "key": "Prep the board (Scripts)"
        },
        {
          "ns": "ui",
          "key": "Connect via Hub"
        },
        {
          "ns": "ui",
          "key": "Verify + Test"
        },
        {
          "ns": "ui",
          "key": "Your sandbox router"
        },
        {
          "ns": "ui",
          "key": "Board"
        },
        {
          "ns": "ui",
          "key": "Identity"
        },
        {
          "ns": "ui",
          "key": "Host"
        },
        {
          "ns": "ui",
          "key": "Mode"
        },
        {
          "ns": "ui",
          "key": "LAN interface"
        },
        {
          "ns": "ui",
          "key": "Hold-down (seconds)"
        },
        {
          "ns": "ui",
          "key": "Coming soon"
        },
        {
          "ns": "ui",
          "key": "Operations"
        },
        {
          "ns": "ui",
          "key": "Business summary"
        },
        {
          "ns": "ui",
          "key": "Revenue today"
        },
        {
          "ns": "ui",
          "key": "Agent"
        },
        {
          "ns": "ui",
          "key": "Owner"
        },
        {
          "ns": "ui",
          "key": "Admin"
        },
        {
          "ns": "ui",
          "key": "Client"
        },
        {
          "ns": "ui",
          "key": "Primary"
        },
        {
          "ns": "ui",
          "key": "User"
        },
        {
          "ns": "ui",
          "key": "MikroMagic Agent"
        },
        {
          "ns": "ui",
          "key": "Expired"
        },
        {
          "ns": "ui",
          "key": "Option A — Cloud Remote (DDNS + TLS)"
        },
        {
          "ns": "ui",
          "key": "Cloud Remote (DDNS + TLS)"
        },
        {
          "ns": "ui",
          "key": "Public IP / DDNS"
        },
        {
          "ns": "ui",
          "key": "Access Points"
        },
        {
          "ns": "ui",
          "key": "Connect a verified controller"
        },
        {
          "ns": "ui",
          "key": "Status"
        },
        {
          "ns": "ui",
          "key": "Guided connector setup"
        },
        {
          "ns": "ui",
          "key": "Pairing code"
        },
        {
          "ns": "ui",
          "key": "Install the agent"
        },
        {
          "ns": "ui",
          "key": "Verify & bind devices"
        },
        {
          "ns": "ui",
          "key": "Add controller"
        },
        {
          "ns": "ui",
          "key": "Easy mode"
        },
        {
          "ns": "ui",
          "key": "Welcome · Myitkyina"
        },
        {
          "ns": "ui",
          "key": "Voucher plans"
        },
        {
          "ns": "ui",
          "key": "Guest portal"
        },
        {
          "ns": "ui",
          "key": "Help and guides"
        },
        {
          "ns": "ui",
          "key": "Account settings"
        },
        {
          "ns": "ui",
          "key": "Track voucher income"
        },
        {
          "ns": "ui",
          "key": "Time and data plans"
        },
        {
          "ns": "ui",
          "key": "Choose your print layout"
        },
        {
          "ns": "ui",
          "key": "Customize the guest welcome page"
        },
        {
          "ns": "ui",
          "key": "Learn how to run your hotspot"
        },
        {
          "ns": "ui",
          "key": "Profile and preferences"
        },
        {
          "ns": "ui",
          "key": "Checking connected routers…"
        },
        {
          "ns": "ui",
          "key": "Could not load your routers"
        },
        {
          "ns": "ui",
          "key": "No physical router connected"
        },
        {
          "ns": "ui",
          "key": "Checking your connected router…"
        },
        {
          "ns": "ui",
          "key": "Could not load your router right now."
        },
        {
          "ns": "ui",
          "key": "Connect a router to see live guests."
        },
        {
          "ns": "ui",
          "key": "Checking live guests…"
        },
        {
          "ns": "ui",
          "key": "Could not read live guests from this router."
        },
        {
          "ns": "ui",
          "key": "No guests are online right now."
        },
        {
          "ns": "ui",
          "key": "Connect router"
        },
        {
          "ns": "ui",
          "key": "Open setup"
        },
        {
          "ns": "ui",
          "key": "Checking your connected routers…"
        },
        {
          "ns": "ui",
          "key": "We could not load your routers. Try again or open Advanced Mode."
        },
        {
          "ns": "ui",
          "key": "Connect a router before setting the Wi-Fi name."
        },
        {
          "ns": "ui",
          "key": "Reading the current Hotspot and Wi-Fi setup…"
        },
        {
          "ns": "ui",
          "key": "We could not read this router. Open Connect router to test it."
        },
        {
          "ns": "ui",
          "key": "The router is ready for Easy Mode setup."
        },
        {
          "ns": "ui",
          "key": "Good evening"
        },
        {
          "ns": "ui",
          "key": "active voucher"
        },
        {
          "ns": "ui",
          "key": "active vouchers"
        },
        {
          "ns": "ui",
          "key": "Connect a physical router before creating vouchers."
        },
        {
          "ns": "ui",
          "key": "Manage batch"
        },
        {
          "ns": "ui",
          "key": "View all"
        },
        {
          "ns": "copy",
          "key": "Emerald and Sapphire include hotspot management with 1 router, 3 sites and 15 access points. Additional capacity is managed through an owner-approved device slot or the relevant account-bound feature key. Sapphire is 104,500 MMK / year (73,150 MMK while the launch offer is active, through 24 Sep 2026). Amethyst is unlimited. Quotas are enforced on the server, so an over-limit add is rejected even on rapid retries."
        },
        {
          "ns": "copy",
          "key": "Vouchers grouped by the plans you created. Gross is settled voucher revenue plus legacy redemptions; net removes refunded orders."
        },
        {
          "ns": "copy",
          "key": "A magician is brewing a new feature..which will be available soon"
        },
        {
          "ns": "copy",
          "key": "Upcoming soon...."
        },
        {
          "ns": "copy",
          "key": "This Operations tab is a quiet preview. No feature details yet — stay tuned."
        },
        {
          "ns": "copy",
          "key": "Privileged tenant access — billing, user management, scripts, backups, and full site control."
        },
        {
          "ns": "copy",
          "key": "Standard tenant access — routers, vouchers, portal, and live sessions for your sites."
        },
        {
          "ns": "copy",
          "key": "Enables a free timed trial session for walk-in guests before they buy a voucher. Uses the mm-trial profile (10 min, 1.5 Mbps). Requires Hotspot and RouterOS 7.1+."
        },
        {
          "ns": "copy",
          "key": "Splits your internet bandwidth fairly across all connected guests so no single user can hog the connection."
        },
        {
          "ns": "copy",
          "key": "Saves a full router config backup every night at 02:30 to the router's flash storage. Named mm-auto-backup."
        },
        {
          "ns": "copy",
          "key": "Partial protection — LAN interface list is missing, so guest DNS bypass is not blocked. Run Magic Hub board prep first."
        },
        {
          "ns": "copy",
          "key": "Pick a connection method first. Cloud Remote needs a public IP. Local Connector needs a paired agent on site. Magic Hub is for Starlink and other CGNAT lines — the RouterBoard dials out to the MikroTik Magic hub. Credentials are encrypted at rest with AES-256-GCM."
        },
        {
          "ns": "copy",
          "key": "Three ways, three names: Magic Hub (Starlink — router calls us, then a paste-script window). Cloud Remote (public IP — we call the router). Local Connector (a PC on site). They are not the same. Credentials are encrypted at rest with AES-256-GCM."
        },
        {
          "ns": "copy",
          "key": "Magic Hub is not Cloud Remote. Tap Add router (not the Magic Hub card). A window then shows the paste script — it is not on the Scripts page."
        },
        {
          "ns": "copy",
          "key": "Magic Hub is the Starlink path. Cloud Remote is a different button."
        },
        {
          "ns": "copy",
          "key": "This window is Magic Hub — not Cloud Remote, not the Scripts page. Copy the commands into WinBox New Terminal."
        },
        {
          "ns": "copy",
          "key": "This window is Magic Hub (Cloud Remote). Copy the commands into WinBox New Terminal. It is not the Scripts page."
        },
        {
          "ns": "copy",
          "key": "Board already has WAN internet (default route). If not, fix DHCP on ether1 first — then come back to this window."
        },
        {
          "ns": "copy",
          "key": "Copy script → WinBox New Terminal → paste once. It sets WireGuard, www-ssl + cert, and rest-api. Safe to paste again."
        },
        {
          "ns": "copy",
          "key": "Tap Connect via Hub (or Add router with Magic Hub selected). A window then shows the paste script. That window is not Cloud Remote and not the Scripts page."
        },
        {
          "ns": "copy",
          "key": "This board is already on Magic Hub. The paste script appears once in a window after Add router or Connect via Hub — not on the Scripts page. If you lost it, Remove then Connect via Hub."
        },
        {
          "ns": "copy",
          "key": "Starlink / CGNAT with no site PC. Add the board on Routers — a paste-script window opens. Not Cloud Remote."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote for Starlink / CGNAT. Add the board — a paste-script window opens."
        },
        {
          "ns": "copy",
          "key": "Starlink / CGNAT, no site PC. After Add router a paste-script window opens. Not Cloud Remote."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote for Starlink / CGNAT. After Add router a paste-script window opens."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote connects over HTTPS (www-ssl, port 443 by default). Keep the self-signed certificate option on for MikroTik Cloud DDNS certificates."
        },
        {
          "ns": "copy",
          "key": "On CGNAT the hostname is only a label — the app will not dial it after WireGuard is connected. Use MikroTik Cloud DDNS or any public DNS name you control."
        },
        {
          "ns": "copy",
          "key": "On CGNAT the hostname is only a label — the app will not dial it after Magic Hub is connected. Use MikroTik Cloud DDNS or any public DNS name you control."
        },
        {
          "ns": "copy",
          "key": "Add the router — the one-time Magic Hub script appears on the card. Paste it on the RouterBoard, then Check now."
        },
        {
          "ns": "copy",
          "key": "RouterBoard dials out to the MikroTik Magic hub. Best for Starlink / CGNAT when you have no always-on PC on site."
        },
        {
          "ns": "copy",
          "key": "After you add the router, use Magic Hub below (always visible on the card) → Connect via Hub → paste the one-time script on the RouterBoard → Check now."
        },
        {
          "ns": "copy",
          "key": "MikroTik Magic is a cloud-hosted web app. It reaches your RouterBoard in three ways: Cloud Remote / Magic Hub (router dials out to the MikroTik Magic VPS — for Starlink and other CGNAT lines), Local Connector (agent on the LAN), or Quick Setup when the WAN has a real public IP / DDNS + HTTPS. This manual covers each path, the tools in the app, and the plan limits that apply to your account."
        },
        {
          "ns": "copy",
          "key": "For Starlink and other CGNAT lines the app cannot dial into the RouterBoard. RouterOS 7 already has WireGuard built in, so the board dials OUT to the MikroTik Magic hosted VPS hub. The hub holds one management peer per RouterBoard; the app then reaches RouterOS REST through the hub. Guest hotspot traffic still leaves via Starlink — the tunnel is management only. WinBox paste blocks live in Scripts (owner) under Magic Hub."
        },
        {
          "ns": "copy",
          "key": "RouterOS 7.1+ only (not TILE CCR1xxx). ether1 = Starlink. This script is hub/REST prep (WAN, LAN, NTP, cert, www-ssl) — not the WireGuard keys and not the full hotspot Master."
        },
        {
          "ns": "copy",
          "key": "The script contains this board’s private key and is shown only once. It already sets tunnel /24 and MTU 1280. Do not invent keys or edit the hub endpoint by hand. Do not put that script in the Scripts library."
        },
        {
          "ns": "copy",
          "key": "Green / Online means the hub can reach www-ssl on the tunnel. Then telemetry, terminal, vouchers and portal deploy work over WireGuard."
        },
        {
          "ns": "copy",
          "key": "confirm the board has WAN internet, the app script was imported, magic-cloud is /24 not /32, and /interface/wireguard/peers shows a recent last-handshake. www-ssl must have a certificate on port 443. Tick Allow self-signed. If Connect via Hub fails in the app, the hosted hub secrets may be missing — contact the owner."
        },
        {
          "ns": "copy",
          "key": "This is a virtual MikroTik stored in your account. Connection checks, Live users, and Vouchers work the same as a real router. Nothing is dialled — not LAN, not Cloud DDNS, not the Singapore hub."
        },
        {
          "ns": "copy",
          "key": "Could not load your sandbox. Try again in a moment."
        },
        {
          "ns": "copy",
          "key": "No sandbox yet."
        },
        {
          "ns": "copy",
          "key": "Create one virtual RB5009. It does not count toward your paid router quota. One per account."
        },
        {
          "ns": "copy",
          "key": "Sandbox is a virtual MikroTik in your account — Live users and Vouchers work without hardware. Real routers are physical devices and every write is gated."
        },
        {
          "ns": "copy",
          "key": "This router is a virtual lab device. Kick, ban and vouchers stay in the app and never reach hardware. Magic Hub and Multi-WAN are not available."
        },
        {
          "ns": "copy",
          "key": "Then set the router up locally on that same machine"
        },
        {
          "ns": "copy",
          "key": "Plug an Ethernet cable from that computer into any RB4011 LAN port (ether2 – ether10) yourself — this is a manual step the app cannot perform. Then run the local setup tool. It asks for the router username and password on that computer only: they are never typed into this page and never sent to MikroMagic."
        },
        {
          "ns": "copy",
          "key": "Local setup tool"
        },
        {
          "ns": "copy",
          "key": "Dark mode is the default look. Switch to light if you prefer brighter browsing — accents stay brand blue → violet either way."
        },
        {
          "ns": "copy",
          "key": "Promoting a router to production needs an owner or admin role plus the exact phrase, for example: \""
        },
        {
          "ns": "copy",
          "key": "Manage the router from anywhere over MikroTik's free xxxx.sn.mynetname.net hostname. Needs a public IP on the WAN line."
        },
        {
          "ns": "copy",
          "key": "A paired agent on the site reaches the router's LAN IP. Works behind CGNAT (Starlink, mobile ISPs) with no port forwarding."
        },
        {
          "ns": "copy",
          "key": "manage UniFi, MikroTik CAPsMAN, Ruijie/Reyee and generic controllers: SSIDs, Wi-Fi passwords, VLANs, radios, reboots, alarms and clients."
        },
        {
          "ns": "copy",
          "key": "full access, sees and manages every account, no expiry, unlimited AI scans."
        },
        {
          "ns": "copy",
          "key": "full operational access including destructive commands; no expiry."
        },
        {
          "ns": "copy",
          "key": "own data only. New accounts are active for 7 days, then flip to Expired automatically until a plan is purchased or the owner reactivates them."
        },
        {
          "ns": "copy",
          "key": "never expires. Earns 15 Magic Coins for every Emerald or Sapphire purchase made by an account they created."
        },
        {
          "ns": "copy",
          "key": "must renew on Services. Your RouterBoard hotspot keeps serving guests. Home, Profile and this manual stay open so you can renew; Live users, Portal, Routers and other cloud ops stay closed until you pay."
        },
        {
          "ns": "copy",
          "key": "Emerald and Sapphire include hotspot management with 1 router, 3 sites and 15 access points. Plus Tier Pass (+30,000 MMK / month on Emerald, or +300,000 MMK / year on Sapphire) adds +1 router, +7 sites and +20 access points. Sapphire is 104,500 MMK / year (73,150 MMK while the launch offer is active, through 24 Sep 2026). Amethyst is unlimited. Quotas are enforced on the server, so an over-limit add is rejected even on rapid retries."
        },
        {
          "ns": "copy",
          "key": "30 manual scans per month on standard plans. Plus Tier Pass accounts get 50 per month; unused scans carry forward and the bank resets every 1 January. Fleet and Security Insights share the same quota."
        },
        {
          "ns": "copy",
          "key": "your plan allows one router, three sites and fifteen access points. Upgrade to Plus Tier Pass from the Pricing page to add more."
        },
        {
          "ns": "copy",
          "key": "Run in an elevated PowerShell"
        },
        {
          "ns": "copy",
          "key": "Run in Terminal"
        },
        {
          "ns": "copy",
          "key": "Online"
        },
        {
          "ns": "copy",
          "key": "Waiting for first heartbeat…"
        },
        {
          "ns": "copy",
          "key": "No access point controllers yet."
        },
        {
          "ns": "copy",
          "key": "No routers yet. Use Quick Setup to add your first one."
        },
        {
          "ns": "copy",
          "key": "Choose the language used across MikroTik Magic. Buttons and feature names stay in English so the app stays consistent."
        },
        {
          "ns": "copy",
          "key": "Platform · active router sites"
        },
        {
          "ns": "copy",
          "key": "Status-only monitor for Developers. Users, MikroMagic Agents, and Expired accounts never see this and their roles are not changed. Active = Magic Hub online or handshake/seen within 5 minutes."
        },
        {
          "ns": "copy",
          "key": "active site(s)"
        },
        {
          "ns": "copy",
          "key": "No sites currently report an active router."
        },
        {
          "ns": "copy",
          "key": "Live on routers"
        },
        {
          "ns": "copy",
          "key": "No uplink"
        },
        {
          "ns": "copy",
          "key": "Four steps: name the connector, mint a one-time pairing code, install the agent on a machine inside the customer LAN, then confirm it is online and bind your devices."
        },
        {
          "ns": "copy",
          "key": "Use the site name so you can tell bridges apart later, for example “Main site bridge”."
        },
        {
          "ns": "copy",
          "key": "The pairing code is shown once and expires in 30 minutes. The agent exchanges it for a permanent token on first contact."
        },
        {
          "ns": "copy",
          "key": "Run the command on any always-on Windows or macOS machine in the same LAN as the routers and access points. It installs a background service that only makes outbound HTTPS calls — no port forwarding."
        },
        {
          "ns": "copy",
          "key": "The agent heartbeats every 30 seconds. Once it shows Online, open Routers or Access Points, pick “Local Connector” as the connection method and select this connector."
        },
        {
          "ns": "copy",
          "key": "The agent heartbeats every 30 seconds. Once it shows Online, open Routers or Advanced → AP integrations, pick “Local Connector” as the connection method and select this connector."
        },
        {
          "ns": "copy",
          "key": "advanced controller links for verified platforms. They are not required when external APs run in bridge mode and are managed in their native app."
        },
        {
          "ns": "copy",
          "key": "Advanced controller links for verified platforms. Connect only a controller you intend to manage from MikroTik Magic; native vendor apps remain the default for other access points."
        },
        {
          "ns": "copy",
          "key": "Manage Wi-Fi across brands — Ubiquiti UniFi, MikroTik CAPsMAN, Ruijie/Reyee and other controllers — from the same console as your routers."
        },
        {
          "ns": "copy",
          "key": "MikroTik access points are reached through a router you already added — no separate credentials needed. For other brands, use a read/write admin account on the controller. Controllers on a private LAN can be reached through a paired local Connector."
        },
        {
          "ns": "copy",
          "key": "Remove the cloud tunnel for {name}?"
        },
        {
          "ns": "copy",
          "key": "This router already has voucher plans from the app. Continue, then type the confirmation phrase. Those profiles will be deleted on the device before the current plans are saved."
        }
      ],
      "actionEntries": []
    },
    "my": {
      "total": 493,
      "translated": 493,
      "coverage": 100,
      "missing": [],
      "todo": [],
      "wrongScript": [],
      "unused": [
        {
          "ns": "ui",
          "key": "Magic Dude"
        },
        {
          "ns": "ui",
          "key": "Trial Guest Access"
        },
        {
          "ns": "ui",
          "key": "Fair Share QoS"
        },
        {
          "ns": "ui",
          "key": "Auto Daily Backup"
        },
        {
          "ns": "ui",
          "key": "Hotspot Operations"
        },
        {
          "ns": "ui",
          "key": "Prep the board (Scripts)"
        },
        {
          "ns": "ui",
          "key": "Connect via Hub"
        },
        {
          "ns": "ui",
          "key": "Verify + Test"
        },
        {
          "ns": "ui",
          "key": "Your sandbox router"
        },
        {
          "ns": "ui",
          "key": "Board"
        },
        {
          "ns": "ui",
          "key": "Identity"
        },
        {
          "ns": "ui",
          "key": "Host"
        },
        {
          "ns": "ui",
          "key": "Mode"
        },
        {
          "ns": "ui",
          "key": "LAN interface"
        },
        {
          "ns": "ui",
          "key": "Hold-down (seconds)"
        },
        {
          "ns": "ui",
          "key": "Coming soon"
        },
        {
          "ns": "ui",
          "key": "Operations"
        },
        {
          "ns": "ui",
          "key": "Business summary"
        },
        {
          "ns": "ui",
          "key": "Revenue today"
        },
        {
          "ns": "ui",
          "key": "Agent"
        },
        {
          "ns": "ui",
          "key": "Owner"
        },
        {
          "ns": "ui",
          "key": "Admin"
        },
        {
          "ns": "ui",
          "key": "Client"
        },
        {
          "ns": "ui",
          "key": "Primary"
        },
        {
          "ns": "ui",
          "key": "User"
        },
        {
          "ns": "ui",
          "key": "MikroMagic Agent"
        },
        {
          "ns": "ui",
          "key": "Expired"
        },
        {
          "ns": "ui",
          "key": "Option A — Cloud Remote (DDNS + TLS)"
        },
        {
          "ns": "ui",
          "key": "Cloud Remote (DDNS + TLS)"
        },
        {
          "ns": "ui",
          "key": "Public IP / DDNS"
        },
        {
          "ns": "ui",
          "key": "Access Points"
        },
        {
          "ns": "ui",
          "key": "Connect a verified controller"
        },
        {
          "ns": "ui",
          "key": "Status"
        },
        {
          "ns": "ui",
          "key": "Guided connector setup"
        },
        {
          "ns": "ui",
          "key": "Pairing code"
        },
        {
          "ns": "ui",
          "key": "Install the agent"
        },
        {
          "ns": "ui",
          "key": "Verify & bind devices"
        },
        {
          "ns": "ui",
          "key": "Add controller"
        },
        {
          "ns": "ui",
          "key": "Easy mode"
        },
        {
          "ns": "ui",
          "key": "Welcome · Myitkyina"
        },
        {
          "ns": "ui",
          "key": "Voucher plans"
        },
        {
          "ns": "ui",
          "key": "Guest portal"
        },
        {
          "ns": "ui",
          "key": "Help and guides"
        },
        {
          "ns": "ui",
          "key": "Account settings"
        },
        {
          "ns": "ui",
          "key": "Track voucher income"
        },
        {
          "ns": "ui",
          "key": "Time and data plans"
        },
        {
          "ns": "ui",
          "key": "Choose your print layout"
        },
        {
          "ns": "ui",
          "key": "Customize the guest welcome page"
        },
        {
          "ns": "ui",
          "key": "Learn how to run your hotspot"
        },
        {
          "ns": "ui",
          "key": "Profile and preferences"
        },
        {
          "ns": "ui",
          "key": "Checking connected routers…"
        },
        {
          "ns": "ui",
          "key": "Could not load your routers"
        },
        {
          "ns": "ui",
          "key": "No physical router connected"
        },
        {
          "ns": "ui",
          "key": "Checking your connected router…"
        },
        {
          "ns": "ui",
          "key": "Could not load your router right now."
        },
        {
          "ns": "ui",
          "key": "Connect a router to see live guests."
        },
        {
          "ns": "ui",
          "key": "Checking live guests…"
        },
        {
          "ns": "ui",
          "key": "Could not read live guests from this router."
        },
        {
          "ns": "ui",
          "key": "No guests are online right now."
        },
        {
          "ns": "ui",
          "key": "Connect router"
        },
        {
          "ns": "ui",
          "key": "Open setup"
        },
        {
          "ns": "ui",
          "key": "Checking your connected routers…"
        },
        {
          "ns": "ui",
          "key": "We could not load your routers. Try again or open Advanced Mode."
        },
        {
          "ns": "ui",
          "key": "Connect a router before setting the Wi-Fi name."
        },
        {
          "ns": "ui",
          "key": "Reading the current Hotspot and Wi-Fi setup…"
        },
        {
          "ns": "ui",
          "key": "We could not read this router. Open Connect router to test it."
        },
        {
          "ns": "ui",
          "key": "The router is ready for Easy Mode setup."
        },
        {
          "ns": "ui",
          "key": "Good evening"
        },
        {
          "ns": "ui",
          "key": "active voucher"
        },
        {
          "ns": "ui",
          "key": "active vouchers"
        },
        {
          "ns": "ui",
          "key": "Connect a physical router before creating vouchers."
        },
        {
          "ns": "ui",
          "key": "Manage batch"
        },
        {
          "ns": "ui",
          "key": "View all"
        },
        {
          "ns": "copy",
          "key": "Emerald and Sapphire include hotspot management with 1 router, 3 sites and 15 access points. Additional capacity is managed through an owner-approved device slot or the relevant account-bound feature key. Sapphire is 104,500 MMK / year (73,150 MMK while the launch offer is active, through 24 Sep 2026). Amethyst is unlimited. Quotas are enforced on the server, so an over-limit add is rejected even on rapid retries."
        },
        {
          "ns": "copy",
          "key": "Vouchers grouped by the plans you created. Gross is settled voucher revenue plus legacy redemptions; net removes refunded orders."
        },
        {
          "ns": "copy",
          "key": "A magician is brewing a new feature..which will be available soon"
        },
        {
          "ns": "copy",
          "key": "Upcoming soon...."
        },
        {
          "ns": "copy",
          "key": "This Operations tab is a quiet preview. No feature details yet — stay tuned."
        },
        {
          "ns": "copy",
          "key": "Privileged tenant access — billing, user management, scripts, backups, and full site control."
        },
        {
          "ns": "copy",
          "key": "Standard tenant access — routers, vouchers, portal, and live sessions for your sites."
        },
        {
          "ns": "copy",
          "key": "Enables a free timed trial session for walk-in guests before they buy a voucher. Uses the mm-trial profile (10 min, 1.5 Mbps). Requires Hotspot and RouterOS 7.1+."
        },
        {
          "ns": "copy",
          "key": "Splits your internet bandwidth fairly across all connected guests so no single user can hog the connection."
        },
        {
          "ns": "copy",
          "key": "Saves a full router config backup every night at 02:30 to the router's flash storage. Named mm-auto-backup."
        },
        {
          "ns": "copy",
          "key": "Partial protection — LAN interface list is missing, so guest DNS bypass is not blocked. Run Magic Hub board prep first."
        },
        {
          "ns": "copy",
          "key": "Pick a connection method first. Cloud Remote needs a public IP. Local Connector needs a paired agent on site. Magic Hub is for Starlink and other CGNAT lines — the RouterBoard dials out to the MikroTik Magic hub. Credentials are encrypted at rest with AES-256-GCM."
        },
        {
          "ns": "copy",
          "key": "Three ways, three names: Magic Hub (Starlink — router calls us, then a paste-script window). Cloud Remote (public IP — we call the router). Local Connector (a PC on site). They are not the same. Credentials are encrypted at rest with AES-256-GCM."
        },
        {
          "ns": "copy",
          "key": "Magic Hub is not Cloud Remote. Tap Add router (not the Magic Hub card). A window then shows the paste script — it is not on the Scripts page."
        },
        {
          "ns": "copy",
          "key": "Magic Hub is the Starlink path. Cloud Remote is a different button."
        },
        {
          "ns": "copy",
          "key": "This window is Magic Hub — not Cloud Remote, not the Scripts page. Copy the commands into WinBox New Terminal."
        },
        {
          "ns": "copy",
          "key": "This window is Magic Hub (Cloud Remote). Copy the commands into WinBox New Terminal. It is not the Scripts page."
        },
        {
          "ns": "copy",
          "key": "Board already has WAN internet (default route). If not, fix DHCP on ether1 first — then come back to this window."
        },
        {
          "ns": "copy",
          "key": "Copy script → WinBox New Terminal → paste once. It sets WireGuard, www-ssl + cert, and rest-api. Safe to paste again."
        },
        {
          "ns": "copy",
          "key": "Tap Connect via Hub (or Add router with Magic Hub selected). A window then shows the paste script. That window is not Cloud Remote and not the Scripts page."
        },
        {
          "ns": "copy",
          "key": "This board is already on Magic Hub. The paste script appears once in a window after Add router or Connect via Hub — not on the Scripts page. If you lost it, Remove then Connect via Hub."
        },
        {
          "ns": "copy",
          "key": "Starlink / CGNAT with no site PC. Add the board on Routers — a paste-script window opens. Not Cloud Remote."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote for Starlink / CGNAT. Add the board — a paste-script window opens."
        },
        {
          "ns": "copy",
          "key": "Starlink / CGNAT, no site PC. After Add router a paste-script window opens. Not Cloud Remote."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote for Starlink / CGNAT. After Add router a paste-script window opens."
        },
        {
          "ns": "copy",
          "key": "On CGNAT the hostname is only a label — the app will not dial it after WireGuard is connected. Use MikroTik Cloud DDNS or any public DNS name you control."
        },
        {
          "ns": "copy",
          "key": "On CGNAT the hostname is only a label — the app will not dial it after Magic Hub is connected. Use MikroTik Cloud DDNS or any public DNS name you control."
        },
        {
          "ns": "copy",
          "key": "Add the router — the one-time Magic Hub script appears on the card. Paste it on the RouterBoard, then Check now."
        },
        {
          "ns": "copy",
          "key": "RouterBoard dials out to the MikroTik Magic hub. Best for Starlink / CGNAT when you have no always-on PC on site."
        },
        {
          "ns": "copy",
          "key": "After you add the router, use Magic Hub below (always visible on the card) → Connect via Hub → paste the one-time script on the RouterBoard → Check now."
        },
        {
          "ns": "copy",
          "key": "Cloud Remote connects over HTTPS (www-ssl, port 443 by default). Keep the self-signed certificate option on for MikroTik Cloud DDNS certificates."
        },
        {
          "ns": "copy",
          "key": "MikroTik Magic is a cloud-hosted web app. It reaches your RouterBoard in three ways: Cloud Remote / Magic Hub (router dials out to the MikroTik Magic VPS — for Starlink and other CGNAT lines), Local Connector (agent on the LAN), or Quick Setup when the WAN has a real public IP / DDNS + HTTPS. This manual covers each path, the tools in the app, and the plan limits that apply to your account."
        },
        {
          "ns": "copy",
          "key": "For Starlink and other CGNAT lines the app cannot dial into the RouterBoard. RouterOS 7 already has WireGuard built in, so the board dials OUT to the MikroTik Magic hosted VPS hub. The hub holds one management peer per RouterBoard; the app then reaches RouterOS REST through the hub. Guest hotspot traffic still leaves via Starlink — the tunnel is management only. WinBox paste blocks live in Scripts (owner) under Magic Hub."
        },
        {
          "ns": "copy",
          "key": "RouterOS 7.1+ only (not TILE CCR1xxx). ether1 = Starlink. This script is hub/REST prep (WAN, LAN, NTP, cert, www-ssl) — not the WireGuard keys and not the full hotspot Master."
        },
        {
          "ns": "copy",
          "key": "The script contains this board’s private key and is shown only once. It already sets tunnel /24 and MTU 1280. Do not invent keys or edit the hub endpoint by hand. Do not put that script in the Scripts library."
        },
        {
          "ns": "copy",
          "key": "Green / Online means the hub can reach www-ssl on the tunnel. Then telemetry, terminal, vouchers and portal deploy work over WireGuard."
        },
        {
          "ns": "copy",
          "key": "confirm the board has WAN internet, the app script was imported, magic-cloud is /24 not /32, and /interface/wireguard/peers shows a recent last-handshake. www-ssl must have a certificate on port 443. Tick Allow self-signed. If Connect via Hub fails in the app, the hosted hub secrets may be missing — contact the owner."
        },
        {
          "ns": "copy",
          "key": "This is a virtual MikroTik stored in your account. Connection checks, Live users, and Vouchers work the same as a real router. Nothing is dialled — not LAN, not Cloud DDNS, not the Singapore hub."
        },
        {
          "ns": "copy",
          "key": "Could not load your sandbox. Try again in a moment."
        },
        {
          "ns": "copy",
          "key": "No sandbox yet."
        },
        {
          "ns": "copy",
          "key": "Create one virtual RB5009. It does not count toward your paid router quota. One per account."
        },
        {
          "ns": "copy",
          "key": "Sandbox is a virtual MikroTik in your account — Live users and Vouchers work without hardware. Real routers are physical devices and every write is gated."
        },
        {
          "ns": "copy",
          "key": "This router is a virtual lab device. Kick, ban and vouchers stay in the app and never reach hardware. Magic Hub and Multi-WAN are not available."
        },
        {
          "ns": "copy",
          "key": "Then set the router up locally on that same machine"
        },
        {
          "ns": "copy",
          "key": "Plug an Ethernet cable from that computer into any RB4011 LAN port (ether2 – ether10) yourself — this is a manual step the app cannot perform. Then run the local setup tool. It asks for the router username and password on that computer only: they are never typed into this page and never sent to MikroMagic."
        },
        {
          "ns": "copy",
          "key": "Local setup tool"
        },
        {
          "ns": "copy",
          "key": "Dark mode is the default look. Switch to light if you prefer brighter browsing — accents stay brand blue → violet either way."
        },
        {
          "ns": "copy",
          "key": "Promoting a router to production needs an owner or admin role plus the exact phrase, for example: \""
        },
        {
          "ns": "copy",
          "key": "Manage the router from anywhere over MikroTik's free xxxx.sn.mynetname.net hostname. Needs a public IP on the WAN line."
        },
        {
          "ns": "copy",
          "key": "A paired agent on the site reaches the router's LAN IP. Works behind CGNAT (Starlink, mobile ISPs) with no port forwarding."
        },
        {
          "ns": "copy",
          "key": "manage UniFi, MikroTik CAPsMAN, Ruijie/Reyee and generic controllers: SSIDs, Wi-Fi passwords, VLANs, radios, reboots, alarms and clients."
        },
        {
          "ns": "copy",
          "key": "full access, sees and manages every account, no expiry, unlimited AI scans."
        },
        {
          "ns": "copy",
          "key": "full operational access including destructive commands; no expiry."
        },
        {
          "ns": "copy",
          "key": "own data only. New accounts are active for 7 days, then flip to Expired automatically until a plan is purchased or the owner reactivates them."
        },
        {
          "ns": "copy",
          "key": "never expires. Earns 15 Magic Coins for every Emerald or Sapphire purchase made by an account they created."
        },
        {
          "ns": "copy",
          "key": "must renew on Services. Your RouterBoard hotspot keeps serving guests. Home, Profile and this manual stay open so you can renew; Live users, Portal, Routers and other cloud ops stay closed until you pay."
        },
        {
          "ns": "copy",
          "key": "Emerald and Sapphire include hotspot management with 1 router, 3 sites and 15 access points. Plus Tier Pass (+30,000 MMK / month on Emerald, or +300,000 MMK / year on Sapphire) adds +1 router, +7 sites and +20 access points. Sapphire is 104,500 MMK / year (73,150 MMK while the launch offer is active, through 24 Sep 2026). Amethyst is unlimited. Quotas are enforced on the server, so an over-limit add is rejected even on rapid retries."
        },
        {
          "ns": "copy",
          "key": "30 manual scans per month on standard plans. Plus Tier Pass accounts get 50 per month; unused scans carry forward and the bank resets every 1 January. Fleet and Security Insights share the same quota."
        },
        {
          "ns": "copy",
          "key": "your plan allows one router, three sites and fifteen access points. Upgrade to Plus Tier Pass from the Pricing page to add more."
        },
        {
          "ns": "copy",
          "key": "Run in an elevated PowerShell"
        },
        {
          "ns": "copy",
          "key": "Run in Terminal"
        },
        {
          "ns": "copy",
          "key": "Online"
        },
        {
          "ns": "copy",
          "key": "Waiting for first heartbeat…"
        },
        {
          "ns": "copy",
          "key": "No access point controllers yet."
        },
        {
          "ns": "copy",
          "key": "No routers yet. Use Quick Setup to add your first one."
        },
        {
          "ns": "copy",
          "key": "Choose the language used across MikroTik Magic. Buttons and feature names stay in English so the app stays consistent."
        },
        {
          "ns": "copy",
          "key": "Platform · active router sites"
        },
        {
          "ns": "copy",
          "key": "Status-only monitor for Developers. Users, MikroMagic Agents, and Expired accounts never see this and their roles are not changed. Active = Magic Hub online or handshake/seen within 5 minutes."
        },
        {
          "ns": "copy",
          "key": "active site(s)"
        },
        {
          "ns": "copy",
          "key": "No sites currently report an active router."
        },
        {
          "ns": "copy",
          "key": "Live on routers"
        },
        {
          "ns": "copy",
          "key": "No uplink"
        },
        {
          "ns": "copy",
          "key": "Four steps: name the connector, mint a one-time pairing code, install the agent on a machine inside the customer LAN, then confirm it is online and bind your devices."
        },
        {
          "ns": "copy",
          "key": "Use the site name so you can tell bridges apart later, for example “Main site bridge”."
        },
        {
          "ns": "copy",
          "key": "The pairing code is shown once and expires in 30 minutes. The agent exchanges it for a permanent token on first contact."
        },
        {
          "ns": "copy",
          "key": "Run the command on any always-on Windows or macOS machine in the same LAN as the routers and access points. It installs a background service that only makes outbound HTTPS calls — no port forwarding."
        },
        {
          "ns": "copy",
          "key": "The agent heartbeats every 30 seconds. Once it shows Online, open Routers or Access Points, pick “Local Connector” as the connection method and select this connector."
        },
        {
          "ns": "copy",
          "key": "The agent heartbeats every 30 seconds. Once it shows Online, open Routers or Advanced → AP integrations, pick “Local Connector” as the connection method and select this connector."
        },
        {
          "ns": "copy",
          "key": "advanced controller links for verified platforms. They are not required when external APs run in bridge mode and are managed in their native app."
        },
        {
          "ns": "copy",
          "key": "Advanced controller links for verified platforms. Connect only a controller you intend to manage from MikroTik Magic; native vendor apps remain the default for other access points."
        },
        {
          "ns": "copy",
          "key": "Manage Wi-Fi across brands — Ubiquiti UniFi, MikroTik CAPsMAN, Ruijie/Reyee and other controllers — from the same console as your routers."
        },
        {
          "ns": "copy",
          "key": "MikroTik access points are reached through a router you already added — no separate credentials needed. For other brands, use a read/write admin account on the controller. Controllers on a private LAN can be reached through a paired local Connector."
        },
        {
          "ns": "copy",
          "key": "Remove the cloud tunnel for {name}?"
        },
        {
          "ns": "copy",
          "key": "This router already has voucher plans from the app. Continue, then type the confirmation phrase. Those profiles will be deleted on the device before the current plans are saved."
        }
      ],
      "actionEntries": []
    }
  },
  "violations": []
};
