#!/usr/bin/env node
/**
 * Static language consistency audit — CI gate.
 *
 *   bun run i18n:audit                 report only, fails on rule violations
 *   bun run i18n:audit --min 100       also fails when coverage drops below 100%
 *   bun run i18n:audit --json path.json  write the machine-readable report
 *   bun run i18n:audit --check-report --report path.ts  fail when the committed report is stale
 *
 * Exit codes: 0 = clean, 1 = rule violation or coverage below --min.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { buildReport, TODO_PREFIX } from "./i18n-core.mjs";

const argv = process.argv.slice(2);
const flag = (name) => {
  const i = argv.indexOf(name);
  return i === -1 ? null : (argv[i + 1] ?? "");
};
const min = flag("--min") == null ? null : Number(flag("--min"));
const jsonPath = flag("--json");
const reportPath = flag("--report") || jsonPath;
const checkReport = argv.includes("--check-report");

const report = await buildReport();
let failed = false;

for (const [lang, r] of Object.entries(report.languages)) {
  console.log(`\n${lang.toUpperCase()} — ${r.translated}/${r.total} (${r.coverage}%)`);
  if (r.missing.length)
    console.log(
      `  untranslated (${r.missing.length}):\n    ${r.missing.map((m) => `${m.ns}: ${m.key}`).join("\n    ")}`,
    );
  if (r.missing.length) failed = true;
  if (r.todo.length)
    console.log(
      `  ${TODO_PREFIX} placeholders (${r.todo.length}):\n    ${r.todo.map((m) => `${m.ns}: ${m.key}`).join("\n    ")}`,
    );
  if (r.todo.length) failed = true;
  if (r.unused.length)
    console.log(`  unused entries — pre-translated, not on screen yet (${r.unused.length})`);
  if (min != null && r.coverage < min) {
    failed = true;
    console.error(`  ! coverage ${r.coverage}% is below the required ${min}%`);
  }
}

for (const v of report.violations) {
  failed = true;
  console.error(`  ! [${v.lang}] ${v.rule}: ${v.detail}`);
}

console.log(`\nSource strings: ${report.sourceCounts.ui} ui · ${report.sourceCounts.copy} copy`);

if (checkReport) {
  if (!reportPath) {
    failed = true;
    console.error("  ! --check-report requires --report <committed report path>");
  } else {
    const committed = readFileSync(reportPath, "utf8");
    const match = committed.match(/"sourceHash":\s*"([a-f0-9]+)"/);
    if (!match || match[1] !== report.sourceHash) {
      failed = true;
      console.error(
        "  ! committed i18n report is stale; run bun run i18n:audit and commit the result",
      );
    }
  }
}

if (jsonPath) {
  mkdirSync(dirname(jsonPath), { recursive: true });
  const body = JSON.stringify(report, null, 2);
  // A `.ts` target emits a typed module so the in-app admin page can import it.
  writeFileSync(
    jsonPath,
    jsonPath.endsWith(".ts")
      ? `// Generated by \`bun run i18n:audit\`. Do not edit by hand.\nimport type { I18nReport } from "./report-types";\n\nexport const i18nReport: I18nReport = ${body};\n`
      : `${body}\n`,
  );
  console.log(`Report written to ${jsonPath}`);
}

process.exit(failed ? 1 : 0);
