/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevUxShellRouteImport } from './routes/dev.ux-shell'
import { Route as DevSitesMapRouteImport } from './routes/dev.sites-map'
import { Route as DevQuickConfigIconsRouteImport } from './routes/dev.quick-config-icons'
import { Route as DevHomeThumbsRouteImport } from './routes/dev.home-thumbs'
import { Route as ApiChatRouteImport } from './routes/api/$chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVouchersRouteImport } from './routes/_authenticated/app.vouchers'
import { Route as AuthenticatedAppVoucherLayoutsRouteImport } from './routes/_authenticated/app.voucher-layouts'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app.users'
import { Route as AuthenticatedAppUsageRouteImport } from './routes/_authenticated/app.usage'
import { Route as AuthenticatedAppTopologyRouteImport } from './routes/_authenticated/app.topology'
import { Route as AuthenticatedAppTestLabRouteImport } from './routes/_authenticated/app.test-lab'
import { Route as AuthenticatedAppTerminalRouteImport } from './routes/_authenticated/app.terminal'
import { Route as AuthenticatedAppTenantsRouteImport } from './routes/_authenticated/app.tenants'
import { Route as AuthenticatedAppSyslogRouteImport } from './routes/_authenticated/app.syslog'
import { Route as AuthenticatedAppSitesRouteImport } from './routes/_authenticated/app.sites'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppScriptsRouteImport } from './routes/_authenticated/app.scripts'
import { Route as AuthenticatedAppRoutersRouteImport } from './routes/_authenticated/app.routers'
import { Route as AuthenticatedAppRevenueRouteImport } from './routes/_authenticated/app.revenue'
import { Route as AuthenticatedAppResellerOperationRouteImport } from './routes/_authenticated/app.reseller-operation'
import { Route as AuthenticatedAppReadinessRouteImport } from './routes/_authenticated/app.readiness'
import { Route as AuthenticatedAppQuickSetupRouteImport } from './routes/_authenticated/app.quick-setup'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPortalRouteImport } from './routes/_authenticated/app.portal'
import { Route as AuthenticatedAppOwnerOperationsRouteImport } from './routes/_authenticated/app.owner-operations'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppManualRouteImport } from './routes/_authenticated/app.manual'
import { Route as AuthenticatedAppMagicDudeRouteImport } from './routes/_authenticated/app.magic-dude'
import { Route as AuthenticatedAppLiveRouteImport } from './routes/_authenticated/app.live'
import { Route as AuthenticatedAppIncidentsRouteImport } from './routes/_authenticated/app.incidents'
import { Route as AuthenticatedAppI18nRouteImport } from './routes/_authenticated/app.i18n'
import { Route as AuthenticatedAppFleetRouteImport } from './routes/_authenticated/app.fleet'
import { Route as AuthenticatedAppEasyRouteImport } from './routes/_authenticated/app.easy'
import { Route as AuthenticatedAppDevicesRouteImport } from './routes/_authenticated/app.devices'
import { Route as AuthenticatedAppDeploymentsRouteImport } from './routes/_authenticated/app.deployments'
import { Route as AuthenticatedAppConnectorsRouteImport } from './routes/_authenticated/app.connectors'
import { Route as AuthenticatedAppBackupsRouteImport } from './routes/_authenticated/app.backups'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAgentRouteImport } from './routes/_authenticated/app.agent'
import { Route as AuthenticatedAppAccessPointsRouteImport } from './routes/_authenticated/app.access-points'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAppTestLabIndexRouteImport } from './routes/_authenticated/app.test-lab.index'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksVoucherMaintenanceRouteImport } from './routes/api/public/hooks/voucher-maintenance'
import { Route as ApiPublicHooksFleetAiScanRouteImport } from './routes/api/public/hooks/fleet-ai-scan'
import { Route as ApiPublicHooksDbBackupRouteImport } from './routes/api/public/hooks/db-backup'
import { Route as ApiPublicConnectorVersionRouteImport } from './routes/api/public/connector/version'
import { Route as ApiPublicConnectorSetupToolRouteImport } from './routes/api/public/connector/setup-tool'
import { Route as ApiPublicConnectorResultRouteImport } from './routes/api/public/connector/result'
import { Route as ApiPublicConnectorPairRouteImport } from './routes/api/public/connector/pair'
import { Route as ApiPublicConnectorJobsRouteImport } from './routes/api/public/connector/jobs'
import { Route as ApiPublicConnectorHeartbeatRouteImport } from './routes/api/public/connector/heartbeat'
import { Route as ApiPublicConnectorDownloadRouteImport } from './routes/api/public/connector/download'
import { Route as ApiPublicConnectorDevicesRouteImport } from './routes/api/public/connector/devices'
import { Route as AuthenticatedAppTestLabSandboxRouteImport } from './routes/_authenticated/app.test-lab.sandbox'
import { Route as AuthenticatedAppTestLabRealRouteImport } from './routes/_authenticated/app.test-lab.real'
import { Route as AuthenticatedAppTestLabMcpRouteImport } from './routes/_authenticated/app.test-lab.mcp'
import { Route as AuthenticatedAppEasyVouchersRouteImport } from './routes/_authenticated/app.easy.vouchers'
import { Route as AuthenticatedAppEasyScreenRouteImport } from './routes/_authenticated/app.easy.$screen'
import { Route as ApiPublicHooksTelegramCallbackRouteImport } from './routes/api/public/hooks/telegram/callback'
import { Route as ApiPublicHooksSyslogTokenRouteImport } from './routes/api/public/hooks/syslog/$token'
import { Route as ApiPublicConnectorInstallWindowsRouteImport } from './routes/api/public/connector/install/windows'
import { Route as ApiPublicConnectorInstallMacosRouteImport } from './routes/api/public/connector/install/macos'
import { Route as ApiPublicConnectorInstallLinuxRouteImport } from './routes/api/public/connector/install/linux'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUxShellRoute = DevUxShellRouteImport.update({
  id: '/dev/ux-shell',
  path: '/dev/ux-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSitesMapRoute = DevSitesMapRouteImport.update({
  id: '/dev/sites-map',
  path: '/dev/sites-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DevQuickConfigIconsRoute = DevQuickConfigIconsRouteImport.update({
  id: '/dev/quick-config-icons',
  path: '/dev/quick-config-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHomeThumbsRoute = DevHomeThumbsRouteImport.update({
  id: '/dev/home-thumbs',
  path: '/dev/home-thumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/$chat',
  path: '/api/$chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVouchersRoute =
  AuthenticatedAppVouchersRouteImport.update({
    id: '/vouchers',
    path: '/vouchers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVoucherLayoutsRoute =
  AuthenticatedAppVoucherLayoutsRouteImport.update({
    id: '/voucher-layouts',
    path: '/voucher-layouts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUsageRoute = AuthenticatedAppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTopologyRoute =
  AuthenticatedAppTopologyRouteImport.update({
    id: '/topology',
    path: '/topology',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTestLabRoute = AuthenticatedAppTestLabRouteImport.update({
  id: '/test-lab',
  path: '/test-lab',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTerminalRoute =
  AuthenticatedAppTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTenantsRoute = AuthenticatedAppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSyslogRoute = AuthenticatedAppSyslogRouteImport.update({
  id: '/syslog',
  path: '/syslog',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSitesRoute = AuthenticatedAppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScriptsRoute = AuthenticatedAppScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoutersRoute = AuthenticatedAppRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRevenueRoute = AuthenticatedAppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppResellerOperationRoute =
  AuthenticatedAppResellerOperationRouteImport.update({
    id: '/reseller-operation',
    path: '/reseller-operation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReadinessRoute =
  AuthenticatedAppReadinessRouteImport.update({
    id: '/readiness',
    path: '/readiness',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuickSetupRoute =
  AuthenticatedAppQuickSetupRouteImport.update({
    id: '/quick-setup',
    path: '/quick-setup',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPortalRoute = AuthenticatedAppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOwnerOperationsRoute =
  AuthenticatedAppOwnerOperationsRouteImport.update({
    id: '/owner-operations',
    path: '/owner-operations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppManualRoute = AuthenticatedAppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMagicDudeRoute =
  AuthenticatedAppMagicDudeRouteImport.update({
    id: '/magic-dude',
    path: '/magic-dude',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLiveRoute = AuthenticatedAppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIncidentsRoute =
  AuthenticatedAppIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppI18nRoute = AuthenticatedAppI18nRouteImport.update({
  id: '/i18n',
  path: '/i18n',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFleetRoute = AuthenticatedAppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEasyRoute = AuthenticatedAppEasyRouteImport.update({
  id: '/easy',
  path: '/easy',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDevicesRoute = AuthenticatedAppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDeploymentsRoute =
  AuthenticatedAppDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConnectorsRoute =
  AuthenticatedAppConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBackupsRoute = AuthenticatedAppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgentRoute = AuthenticatedAppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccessPointsRoute =
  AuthenticatedAppAccessPointsRouteImport.update({
    id: '/access-points',
    path: '/access-points',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTestLabIndexRoute =
  AuthenticatedAppTestLabIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTestLabRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVoucherMaintenanceRoute =
  ApiPublicHooksVoucherMaintenanceRouteImport.update({
    id: '/api/public/hooks/voucher-maintenance',
    path: '/api/public/hooks/voucher-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFleetAiScanRoute =
  ApiPublicHooksFleetAiScanRouteImport.update({
    id: '/api/public/hooks/fleet-ai-scan',
    path: '/api/public/hooks/fleet-ai-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDbBackupRoute = ApiPublicHooksDbBackupRouteImport.update({
  id: '/api/public/hooks/db-backup',
  path: '/api/public/hooks/db-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectorVersionRoute =
  ApiPublicConnectorVersionRouteImport.update({
    id: '/api/public/connector/version',
    path: '/api/public/connector/version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorSetupToolRoute =
  ApiPublicConnectorSetupToolRouteImport.update({
    id: '/api/public/connector/setup-tool',
    path: '/api/public/connector/setup-tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorResultRoute =
  ApiPublicConnectorResultRouteImport.update({
    id: '/api/public/connector/result',
    path: '/api/public/connector/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorPairRoute = ApiPublicConnectorPairRouteImport.update({
  id: '/api/public/connector/pair',
  path: '/api/public/connector/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectorJobsRoute = ApiPublicConnectorJobsRouteImport.update({
  id: '/api/public/connector/jobs',
  path: '/api/public/connector/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectorHeartbeatRoute =
  ApiPublicConnectorHeartbeatRouteImport.update({
    id: '/api/public/connector/heartbeat',
    path: '/api/public/connector/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorDownloadRoute =
  ApiPublicConnectorDownloadRouteImport.update({
    id: '/api/public/connector/download',
    path: '/api/public/connector/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorDevicesRoute =
  ApiPublicConnectorDevicesRouteImport.update({
    id: '/api/public/connector/devices',
    path: '/api/public/connector/devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppTestLabSandboxRoute =
  AuthenticatedAppTestLabSandboxRouteImport.update({
    id: '/sandbox',
    path: '/sandbox',
    getParentRoute: () => AuthenticatedAppTestLabRoute,
  } as any)
const AuthenticatedAppTestLabRealRoute =
  AuthenticatedAppTestLabRealRouteImport.update({
    id: '/real',
    path: '/real',
    getParentRoute: () => AuthenticatedAppTestLabRoute,
  } as any)
const AuthenticatedAppTestLabMcpRoute =
  AuthenticatedAppTestLabMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthenticatedAppTestLabRoute,
  } as any)
const AuthenticatedAppEasyVouchersRoute =
  AuthenticatedAppEasyVouchersRouteImport.update({
    id: '/vouchers',
    path: '/vouchers',
    getParentRoute: () => AuthenticatedAppEasyRoute,
  } as any)
const AuthenticatedAppEasyScreenRoute =
  AuthenticatedAppEasyScreenRouteImport.update({
    id: '/$screen',
    path: '/$screen',
    getParentRoute: () => AuthenticatedAppEasyRoute,
  } as any)
const ApiPublicHooksTelegramCallbackRoute =
  ApiPublicHooksTelegramCallbackRouteImport.update({
    id: '/api/public/hooks/telegram/callback',
    path: '/api/public/hooks/telegram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyslogTokenRoute =
  ApiPublicHooksSyslogTokenRouteImport.update({
    id: '/api/public/hooks/syslog/$token',
    path: '/api/public/hooks/syslog/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorInstallWindowsRoute =
  ApiPublicConnectorInstallWindowsRouteImport.update({
    id: '/api/public/connector/install/windows',
    path: '/api/public/connector/install/windows',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorInstallMacosRoute =
  ApiPublicConnectorInstallMacosRouteImport.update({
    id: '/api/public/connector/install/macos',
    path: '/api/public/connector/install/macos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectorInstallLinuxRoute =
  ApiPublicConnectorInstallLinuxRouteImport.update({
    id: '/api/public/connector/install/linux',
    path: '/api/public/connector/install/linux',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/$chat': typeof ApiChatRoute
  '/dev/home-thumbs': typeof DevHomeThumbsRoute
  '/dev/quick-config-icons': typeof DevQuickConfigIconsRoute
  '/dev/sites-map': typeof DevSitesMapRoute
  '/dev/ux-shell': typeof DevUxShellRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/access-points': typeof AuthenticatedAppAccessPointsRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/backups': typeof AuthenticatedAppBackupsRoute
  '/app/connectors': typeof AuthenticatedAppConnectorsRoute
  '/app/deployments': typeof AuthenticatedAppDeploymentsRoute
  '/app/devices': typeof AuthenticatedAppDevicesRoute
  '/app/easy': typeof AuthenticatedAppEasyRouteWithChildren
  '/app/fleet': typeof AuthenticatedAppFleetRoute
  '/app/i18n': typeof AuthenticatedAppI18nRoute
  '/app/incidents': typeof AuthenticatedAppIncidentsRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/magic-dude': typeof AuthenticatedAppMagicDudeRoute
  '/app/manual': typeof AuthenticatedAppManualRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/owner-operations': typeof AuthenticatedAppOwnerOperationsRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/quick-setup': typeof AuthenticatedAppQuickSetupRoute
  '/app/readiness': typeof AuthenticatedAppReadinessRoute
  '/app/reseller-operation': typeof AuthenticatedAppResellerOperationRoute
  '/app/revenue': typeof AuthenticatedAppRevenueRoute
  '/app/routers': typeof AuthenticatedAppRoutersRoute
  '/app/scripts': typeof AuthenticatedAppScriptsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/sites': typeof AuthenticatedAppSitesRoute
  '/app/syslog': typeof AuthenticatedAppSyslogRoute
  '/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/app/test-lab': typeof AuthenticatedAppTestLabRouteWithChildren
  '/app/topology': typeof AuthenticatedAppTopologyRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/voucher-layouts': typeof AuthenticatedAppVoucherLayoutsRoute
  '/app/vouchers': typeof AuthenticatedAppVouchersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/easy/$screen': typeof AuthenticatedAppEasyScreenRoute
  '/app/easy/vouchers': typeof AuthenticatedAppEasyVouchersRoute
  '/app/test-lab/mcp': typeof AuthenticatedAppTestLabMcpRoute
  '/app/test-lab/real': typeof AuthenticatedAppTestLabRealRoute
  '/app/test-lab/sandbox': typeof AuthenticatedAppTestLabSandboxRoute
  '/api/public/connector/devices': typeof ApiPublicConnectorDevicesRoute
  '/api/public/connector/download': typeof ApiPublicConnectorDownloadRoute
  '/api/public/connector/heartbeat': typeof ApiPublicConnectorHeartbeatRoute
  '/api/public/connector/jobs': typeof ApiPublicConnectorJobsRoute
  '/api/public/connector/pair': typeof ApiPublicConnectorPairRoute
  '/api/public/connector/result': typeof ApiPublicConnectorResultRoute
  '/api/public/connector/setup-tool': typeof ApiPublicConnectorSetupToolRoute
  '/api/public/connector/version': typeof ApiPublicConnectorVersionRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
  '/api/public/hooks/fleet-ai-scan': typeof ApiPublicHooksFleetAiScanRoute
  '/api/public/hooks/voucher-maintenance': typeof ApiPublicHooksVoucherMaintenanceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/app/test-lab/': typeof AuthenticatedAppTestLabIndexRoute
  '/api/public/connector/install/linux': typeof ApiPublicConnectorInstallLinuxRoute
  '/api/public/connector/install/macos': typeof ApiPublicConnectorInstallMacosRoute
  '/api/public/connector/install/windows': typeof ApiPublicConnectorInstallWindowsRoute
  '/api/public/hooks/syslog/$token': typeof ApiPublicHooksSyslogTokenRoute
  '/api/public/hooks/telegram/callback': typeof ApiPublicHooksTelegramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/$chat': typeof ApiChatRoute
  '/dev/home-thumbs': typeof DevHomeThumbsRoute
  '/dev/quick-config-icons': typeof DevQuickConfigIconsRoute
  '/dev/sites-map': typeof DevSitesMapRoute
  '/dev/ux-shell': typeof DevUxShellRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/access-points': typeof AuthenticatedAppAccessPointsRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/backups': typeof AuthenticatedAppBackupsRoute
  '/app/connectors': typeof AuthenticatedAppConnectorsRoute
  '/app/deployments': typeof AuthenticatedAppDeploymentsRoute
  '/app/devices': typeof AuthenticatedAppDevicesRoute
  '/app/easy': typeof AuthenticatedAppEasyRouteWithChildren
  '/app/fleet': typeof AuthenticatedAppFleetRoute
  '/app/i18n': typeof AuthenticatedAppI18nRoute
  '/app/incidents': typeof AuthenticatedAppIncidentsRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/magic-dude': typeof AuthenticatedAppMagicDudeRoute
  '/app/manual': typeof AuthenticatedAppManualRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/owner-operations': typeof AuthenticatedAppOwnerOperationsRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/quick-setup': typeof AuthenticatedAppQuickSetupRoute
  '/app/readiness': typeof AuthenticatedAppReadinessRoute
  '/app/reseller-operation': typeof AuthenticatedAppResellerOperationRoute
  '/app/revenue': typeof AuthenticatedAppRevenueRoute
  '/app/routers': typeof AuthenticatedAppRoutersRoute
  '/app/scripts': typeof AuthenticatedAppScriptsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/sites': typeof AuthenticatedAppSitesRoute
  '/app/syslog': typeof AuthenticatedAppSyslogRoute
  '/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/app/topology': typeof AuthenticatedAppTopologyRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/voucher-layouts': typeof AuthenticatedAppVoucherLayoutsRoute
  '/app/vouchers': typeof AuthenticatedAppVouchersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/easy/$screen': typeof AuthenticatedAppEasyScreenRoute
  '/app/easy/vouchers': typeof AuthenticatedAppEasyVouchersRoute
  '/app/test-lab/mcp': typeof AuthenticatedAppTestLabMcpRoute
  '/app/test-lab/real': typeof AuthenticatedAppTestLabRealRoute
  '/app/test-lab/sandbox': typeof AuthenticatedAppTestLabSandboxRoute
  '/api/public/connector/devices': typeof ApiPublicConnectorDevicesRoute
  '/api/public/connector/download': typeof ApiPublicConnectorDownloadRoute
  '/api/public/connector/heartbeat': typeof ApiPublicConnectorHeartbeatRoute
  '/api/public/connector/jobs': typeof ApiPublicConnectorJobsRoute
  '/api/public/connector/pair': typeof ApiPublicConnectorPairRoute
  '/api/public/connector/result': typeof ApiPublicConnectorResultRoute
  '/api/public/connector/setup-tool': typeof ApiPublicConnectorSetupToolRoute
  '/api/public/connector/version': typeof ApiPublicConnectorVersionRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
  '/api/public/hooks/fleet-ai-scan': typeof ApiPublicHooksFleetAiScanRoute
  '/api/public/hooks/voucher-maintenance': typeof ApiPublicHooksVoucherMaintenanceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/app/test-lab': typeof AuthenticatedAppTestLabIndexRoute
  '/api/public/connector/install/linux': typeof ApiPublicConnectorInstallLinuxRoute
  '/api/public/connector/install/macos': typeof ApiPublicConnectorInstallMacosRoute
  '/api/public/connector/install/windows': typeof ApiPublicConnectorInstallWindowsRoute
  '/api/public/hooks/syslog/$token': typeof ApiPublicHooksSyslogTokenRoute
  '/api/public/hooks/telegram/callback': typeof ApiPublicHooksTelegramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/$chat': typeof ApiChatRoute
  '/dev/home-thumbs': typeof DevHomeThumbsRoute
  '/dev/quick-config-icons': typeof DevQuickConfigIconsRoute
  '/dev/sites-map': typeof DevSitesMapRoute
  '/dev/ux-shell': typeof DevUxShellRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/access-points': typeof AuthenticatedAppAccessPointsRoute
  '/_authenticated/app/agent': typeof AuthenticatedAppAgentRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/backups': typeof AuthenticatedAppBackupsRoute
  '/_authenticated/app/connectors': typeof AuthenticatedAppConnectorsRoute
  '/_authenticated/app/deployments': typeof AuthenticatedAppDeploymentsRoute
  '/_authenticated/app/devices': typeof AuthenticatedAppDevicesRoute
  '/_authenticated/app/easy': typeof AuthenticatedAppEasyRouteWithChildren
  '/_authenticated/app/fleet': typeof AuthenticatedAppFleetRoute
  '/_authenticated/app/i18n': typeof AuthenticatedAppI18nRoute
  '/_authenticated/app/incidents': typeof AuthenticatedAppIncidentsRoute
  '/_authenticated/app/live': typeof AuthenticatedAppLiveRoute
  '/_authenticated/app/magic-dude': typeof AuthenticatedAppMagicDudeRoute
  '/_authenticated/app/manual': typeof AuthenticatedAppManualRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/owner-operations': typeof AuthenticatedAppOwnerOperationsRoute
  '/_authenticated/app/portal': typeof AuthenticatedAppPortalRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/quick-setup': typeof AuthenticatedAppQuickSetupRoute
  '/_authenticated/app/readiness': typeof AuthenticatedAppReadinessRoute
  '/_authenticated/app/reseller-operation': typeof AuthenticatedAppResellerOperationRoute
  '/_authenticated/app/revenue': typeof AuthenticatedAppRevenueRoute
  '/_authenticated/app/routers': typeof AuthenticatedAppRoutersRoute
  '/_authenticated/app/scripts': typeof AuthenticatedAppScriptsRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/sites': typeof AuthenticatedAppSitesRoute
  '/_authenticated/app/syslog': typeof AuthenticatedAppSyslogRoute
  '/_authenticated/app/tenants': typeof AuthenticatedAppTenantsRoute
  '/_authenticated/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/_authenticated/app/test-lab': typeof AuthenticatedAppTestLabRouteWithChildren
  '/_authenticated/app/topology': typeof AuthenticatedAppTopologyRoute
  '/_authenticated/app/usage': typeof AuthenticatedAppUsageRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/voucher-layouts': typeof AuthenticatedAppVoucherLayoutsRoute
  '/_authenticated/app/vouchers': typeof AuthenticatedAppVouchersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/easy/$screen': typeof AuthenticatedAppEasyScreenRoute
  '/_authenticated/app/easy/vouchers': typeof AuthenticatedAppEasyVouchersRoute
  '/_authenticated/app/test-lab/mcp': typeof AuthenticatedAppTestLabMcpRoute
  '/_authenticated/app/test-lab/real': typeof AuthenticatedAppTestLabRealRoute
  '/_authenticated/app/test-lab/sandbox': typeof AuthenticatedAppTestLabSandboxRoute
  '/api/public/connector/devices': typeof ApiPublicConnectorDevicesRoute
  '/api/public/connector/download': typeof ApiPublicConnectorDownloadRoute
  '/api/public/connector/heartbeat': typeof ApiPublicConnectorHeartbeatRoute
  '/api/public/connector/jobs': typeof ApiPublicConnectorJobsRoute
  '/api/public/connector/pair': typeof ApiPublicConnectorPairRoute
  '/api/public/connector/result': typeof ApiPublicConnectorResultRoute
  '/api/public/connector/setup-tool': typeof ApiPublicConnectorSetupToolRoute
  '/api/public/connector/version': typeof ApiPublicConnectorVersionRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
  '/api/public/hooks/fleet-ai-scan': typeof ApiPublicHooksFleetAiScanRoute
  '/api/public/hooks/voucher-maintenance': typeof ApiPublicHooksVoucherMaintenanceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/app/test-lab/': typeof AuthenticatedAppTestLabIndexRoute
  '/api/public/connector/install/linux': typeof ApiPublicConnectorInstallLinuxRoute
  '/api/public/connector/install/macos': typeof ApiPublicConnectorInstallMacosRoute
  '/api/public/connector/install/windows': typeof ApiPublicConnectorInstallWindowsRoute
  '/api/public/hooks/syslog/$token': typeof ApiPublicHooksSyslogTokenRoute
  '/api/public/hooks/telegram/callback': typeof ApiPublicHooksTelegramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/api/$chat'
    | '/dev/home-thumbs'
    | '/dev/quick-config-icons'
    | '/dev/sites-map'
    | '/dev/ux-shell'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/access-points'
    | '/app/agent'
    | '/app/audit'
    | '/app/backups'
    | '/app/connectors'
    | '/app/deployments'
    | '/app/devices'
    | '/app/easy'
    | '/app/fleet'
    | '/app/i18n'
    | '/app/incidents'
    | '/app/live'
    | '/app/magic-dude'
    | '/app/manual'
    | '/app/orders'
    | '/app/owner-operations'
    | '/app/portal'
    | '/app/profile'
    | '/app/quick-setup'
    | '/app/readiness'
    | '/app/reseller-operation'
    | '/app/revenue'
    | '/app/routers'
    | '/app/scripts'
    | '/app/services'
    | '/app/sites'
    | '/app/syslog'
    | '/app/tenants'
    | '/app/terminal'
    | '/app/test-lab'
    | '/app/topology'
    | '/app/usage'
    | '/app/users'
    | '/app/voucher-layouts'
    | '/app/vouchers'
    | '/app/'
    | '/app/easy/$screen'
    | '/app/easy/vouchers'
    | '/app/test-lab/mcp'
    | '/app/test-lab/real'
    | '/app/test-lab/sandbox'
    | '/api/public/connector/devices'
    | '/api/public/connector/download'
    | '/api/public/connector/heartbeat'
    | '/api/public/connector/jobs'
    | '/api/public/connector/pair'
    | '/api/public/connector/result'
    | '/api/public/connector/setup-tool'
    | '/api/public/connector/version'
    | '/api/public/hooks/db-backup'
    | '/api/public/hooks/fleet-ai-scan'
    | '/api/public/hooks/voucher-maintenance'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/app/test-lab/'
    | '/api/public/connector/install/linux'
    | '/api/public/connector/install/macos'
    | '/api/public/connector/install/windows'
    | '/api/public/hooks/syslog/$token'
    | '/api/public/hooks/telegram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/$chat'
    | '/dev/home-thumbs'
    | '/dev/quick-config-icons'
    | '/dev/sites-map'
    | '/dev/ux-shell'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/access-points'
    | '/app/agent'
    | '/app/audit'
    | '/app/backups'
    | '/app/connectors'
    | '/app/deployments'
    | '/app/devices'
    | '/app/easy'
    | '/app/fleet'
    | '/app/i18n'
    | '/app/incidents'
    | '/app/live'
    | '/app/magic-dude'
    | '/app/manual'
    | '/app/orders'
    | '/app/owner-operations'
    | '/app/portal'
    | '/app/profile'
    | '/app/quick-setup'
    | '/app/readiness'
    | '/app/reseller-operation'
    | '/app/revenue'
    | '/app/routers'
    | '/app/scripts'
    | '/app/services'
    | '/app/sites'
    | '/app/syslog'
    | '/app/tenants'
    | '/app/terminal'
    | '/app/topology'
    | '/app/usage'
    | '/app/users'
    | '/app/voucher-layouts'
    | '/app/vouchers'
    | '/app'
    | '/app/easy/$screen'
    | '/app/easy/vouchers'
    | '/app/test-lab/mcp'
    | '/app/test-lab/real'
    | '/app/test-lab/sandbox'
    | '/api/public/connector/devices'
    | '/api/public/connector/download'
    | '/api/public/connector/heartbeat'
    | '/api/public/connector/jobs'
    | '/api/public/connector/pair'
    | '/api/public/connector/result'
    | '/api/public/connector/setup-tool'
    | '/api/public/connector/version'
    | '/api/public/hooks/db-backup'
    | '/api/public/hooks/fleet-ai-scan'
    | '/api/public/hooks/voucher-maintenance'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/app/test-lab'
    | '/api/public/connector/install/linux'
    | '/api/public/connector/install/macos'
    | '/api/public/connector/install/windows'
    | '/api/public/hooks/syslog/$token'
    | '/api/public/hooks/telegram/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/pricing'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/api/$chat'
    | '/dev/home-thumbs'
    | '/dev/quick-config-icons'
    | '/dev/sites-map'
    | '/dev/ux-shell'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/access-points'
    | '/_authenticated/app/agent'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/backups'
    | '/_authenticated/app/connectors'
    | '/_authenticated/app/deployments'
    | '/_authenticated/app/devices'
    | '/_authenticated/app/easy'
    | '/_authenticated/app/fleet'
    | '/_authenticated/app/i18n'
    | '/_authenticated/app/incidents'
    | '/_authenticated/app/live'
    | '/_authenticated/app/magic-dude'
    | '/_authenticated/app/manual'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/owner-operations'
    | '/_authenticated/app/portal'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/quick-setup'
    | '/_authenticated/app/readiness'
    | '/_authenticated/app/reseller-operation'
    | '/_authenticated/app/revenue'
    | '/_authenticated/app/routers'
    | '/_authenticated/app/scripts'
    | '/_authenticated/app/services'
    | '/_authenticated/app/sites'
    | '/_authenticated/app/syslog'
    | '/_authenticated/app/tenants'
    | '/_authenticated/app/terminal'
    | '/_authenticated/app/test-lab'
    | '/_authenticated/app/topology'
    | '/_authenticated/app/usage'
    | '/_authenticated/app/users'
    | '/_authenticated/app/voucher-layouts'
    | '/_authenticated/app/vouchers'
    | '/_authenticated/app/'
    | '/_authenticated/app/easy/$screen'
    | '/_authenticated/app/easy/vouchers'
    | '/_authenticated/app/test-lab/mcp'
    | '/_authenticated/app/test-lab/real'
    | '/_authenticated/app/test-lab/sandbox'
    | '/api/public/connector/devices'
    | '/api/public/connector/download'
    | '/api/public/connector/heartbeat'
    | '/api/public/connector/jobs'
    | '/api/public/connector/pair'
    | '/api/public/connector/result'
    | '/api/public/connector/setup-tool'
    | '/api/public/connector/version'
    | '/api/public/hooks/db-backup'
    | '/api/public/hooks/fleet-ai-scan'
    | '/api/public/hooks/voucher-maintenance'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/app/test-lab/'
    | '/api/public/connector/install/linux'
    | '/api/public/connector/install/macos'
    | '/api/public/connector/install/windows'
    | '/api/public/hooks/syslog/$token'
    | '/api/public/hooks/telegram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DevHomeThumbsRoute: typeof DevHomeThumbsRoute
  DevQuickConfigIconsRoute: typeof DevQuickConfigIconsRoute
  DevSitesMapRoute: typeof DevSitesMapRoute
  DevUxShellRoute: typeof DevUxShellRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicConnectorDevicesRoute: typeof ApiPublicConnectorDevicesRoute
  ApiPublicConnectorDownloadRoute: typeof ApiPublicConnectorDownloadRoute
  ApiPublicConnectorHeartbeatRoute: typeof ApiPublicConnectorHeartbeatRoute
  ApiPublicConnectorJobsRoute: typeof ApiPublicConnectorJobsRoute
  ApiPublicConnectorPairRoute: typeof ApiPublicConnectorPairRoute
  ApiPublicConnectorResultRoute: typeof ApiPublicConnectorResultRoute
  ApiPublicConnectorSetupToolRoute: typeof ApiPublicConnectorSetupToolRoute
  ApiPublicConnectorVersionRoute: typeof ApiPublicConnectorVersionRoute
  ApiPublicHooksDbBackupRoute: typeof ApiPublicHooksDbBackupRoute
  ApiPublicHooksFleetAiScanRoute: typeof ApiPublicHooksFleetAiScanRoute
  ApiPublicHooksVoucherMaintenanceRoute: typeof ApiPublicHooksVoucherMaintenanceRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  ApiPublicConnectorInstallLinuxRoute: typeof ApiPublicConnectorInstallLinuxRoute
  ApiPublicConnectorInstallMacosRoute: typeof ApiPublicConnectorInstallMacosRoute
  ApiPublicConnectorInstallWindowsRoute: typeof ApiPublicConnectorInstallWindowsRoute
  ApiPublicHooksSyslogTokenRoute: typeof ApiPublicHooksSyslogTokenRoute
  ApiPublicHooksTelegramCallbackRoute: typeof ApiPublicHooksTelegramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ux-shell': {
      id: '/dev/ux-shell'
      path: '/dev/ux-shell'
      fullPath: '/dev/ux-shell'
      preLoaderRoute: typeof DevUxShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sites-map': {
      id: '/dev/sites-map'
      path: '/dev/sites-map'
      fullPath: '/dev/sites-map'
      preLoaderRoute: typeof DevSitesMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/quick-config-icons': {
      id: '/dev/quick-config-icons'
      path: '/dev/quick-config-icons'
      fullPath: '/dev/quick-config-icons'
      preLoaderRoute: typeof DevQuickConfigIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/home-thumbs': {
      id: '/dev/home-thumbs'
      path: '/dev/home-thumbs'
      fullPath: '/dev/home-thumbs'
      preLoaderRoute: typeof DevHomeThumbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$chat': {
      id: '/api/$chat'
      path: '/api/$chat'
      fullPath: '/api/$chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vouchers': {
      id: '/_authenticated/app/vouchers'
      path: '/vouchers'
      fullPath: '/app/vouchers'
      preLoaderRoute: typeof AuthenticatedAppVouchersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/voucher-layouts': {
      id: '/_authenticated/app/voucher-layouts'
      path: '/voucher-layouts'
      fullPath: '/app/voucher-layouts'
      preLoaderRoute: typeof AuthenticatedAppVoucherLayoutsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/usage': {
      id: '/_authenticated/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AuthenticatedAppUsageRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/topology': {
      id: '/_authenticated/app/topology'
      path: '/topology'
      fullPath: '/app/topology'
      preLoaderRoute: typeof AuthenticatedAppTopologyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/test-lab': {
      id: '/_authenticated/app/test-lab'
      path: '/test-lab'
      fullPath: '/app/test-lab'
      preLoaderRoute: typeof AuthenticatedAppTestLabRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/terminal': {
      id: '/_authenticated/app/terminal'
      path: '/terminal'
      fullPath: '/app/terminal'
      preLoaderRoute: typeof AuthenticatedAppTerminalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tenants': {
      id: '/_authenticated/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AuthenticatedAppTenantsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/syslog': {
      id: '/_authenticated/app/syslog'
      path: '/syslog'
      fullPath: '/app/syslog'
      preLoaderRoute: typeof AuthenticatedAppSyslogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sites': {
      id: '/_authenticated/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AuthenticatedAppSitesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scripts': {
      id: '/_authenticated/app/scripts'
      path: '/scripts'
      fullPath: '/app/scripts'
      preLoaderRoute: typeof AuthenticatedAppScriptsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/routers': {
      id: '/_authenticated/app/routers'
      path: '/routers'
      fullPath: '/app/routers'
      preLoaderRoute: typeof AuthenticatedAppRoutersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/revenue': {
      id: '/_authenticated/app/revenue'
      path: '/revenue'
      fullPath: '/app/revenue'
      preLoaderRoute: typeof AuthenticatedAppRevenueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reseller-operation': {
      id: '/_authenticated/app/reseller-operation'
      path: '/reseller-operation'
      fullPath: '/app/reseller-operation'
      preLoaderRoute: typeof AuthenticatedAppResellerOperationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/readiness': {
      id: '/_authenticated/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AuthenticatedAppReadinessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quick-setup': {
      id: '/_authenticated/app/quick-setup'
      path: '/quick-setup'
      fullPath: '/app/quick-setup'
      preLoaderRoute: typeof AuthenticatedAppQuickSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portal': {
      id: '/_authenticated/app/portal'
      path: '/portal'
      fullPath: '/app/portal'
      preLoaderRoute: typeof AuthenticatedAppPortalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/owner-operations': {
      id: '/_authenticated/app/owner-operations'
      path: '/owner-operations'
      fullPath: '/app/owner-operations'
      preLoaderRoute: typeof AuthenticatedAppOwnerOperationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/manual': {
      id: '/_authenticated/app/manual'
      path: '/manual'
      fullPath: '/app/manual'
      preLoaderRoute: typeof AuthenticatedAppManualRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/magic-dude': {
      id: '/_authenticated/app/magic-dude'
      path: '/magic-dude'
      fullPath: '/app/magic-dude'
      preLoaderRoute: typeof AuthenticatedAppMagicDudeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/live': {
      id: '/_authenticated/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AuthenticatedAppLiveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/incidents': {
      id: '/_authenticated/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AuthenticatedAppIncidentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/i18n': {
      id: '/_authenticated/app/i18n'
      path: '/i18n'
      fullPath: '/app/i18n'
      preLoaderRoute: typeof AuthenticatedAppI18nRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fleet': {
      id: '/_authenticated/app/fleet'
      path: '/fleet'
      fullPath: '/app/fleet'
      preLoaderRoute: typeof AuthenticatedAppFleetRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/easy': {
      id: '/_authenticated/app/easy'
      path: '/easy'
      fullPath: '/app/easy'
      preLoaderRoute: typeof AuthenticatedAppEasyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/devices': {
      id: '/_authenticated/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AuthenticatedAppDevicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deployments': {
      id: '/_authenticated/app/deployments'
      path: '/deployments'
      fullPath: '/app/deployments'
      preLoaderRoute: typeof AuthenticatedAppDeploymentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connectors': {
      id: '/_authenticated/app/connectors'
      path: '/connectors'
      fullPath: '/app/connectors'
      preLoaderRoute: typeof AuthenticatedAppConnectorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/backups': {
      id: '/_authenticated/app/backups'
      path: '/backups'
      fullPath: '/app/backups'
      preLoaderRoute: typeof AuthenticatedAppBackupsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agent': {
      id: '/_authenticated/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AuthenticatedAppAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/access-points': {
      id: '/_authenticated/app/access-points'
      path: '/access-points'
      fullPath: '/app/access-points'
      preLoaderRoute: typeof AuthenticatedAppAccessPointsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/test-lab/': {
      id: '/_authenticated/app/test-lab/'
      path: '/'
      fullPath: '/app/test-lab/'
      preLoaderRoute: typeof AuthenticatedAppTestLabIndexRouteImport
      parentRoute: typeof AuthenticatedAppTestLabRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/voucher-maintenance': {
      id: '/api/public/hooks/voucher-maintenance'
      path: '/api/public/hooks/voucher-maintenance'
      fullPath: '/api/public/hooks/voucher-maintenance'
      preLoaderRoute: typeof ApiPublicHooksVoucherMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fleet-ai-scan': {
      id: '/api/public/hooks/fleet-ai-scan'
      path: '/api/public/hooks/fleet-ai-scan'
      fullPath: '/api/public/hooks/fleet-ai-scan'
      preLoaderRoute: typeof ApiPublicHooksFleetAiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/db-backup': {
      id: '/api/public/hooks/db-backup'
      path: '/api/public/hooks/db-backup'
      fullPath: '/api/public/hooks/db-backup'
      preLoaderRoute: typeof ApiPublicHooksDbBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/version': {
      id: '/api/public/connector/version'
      path: '/api/public/connector/version'
      fullPath: '/api/public/connector/version'
      preLoaderRoute: typeof ApiPublicConnectorVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/setup-tool': {
      id: '/api/public/connector/setup-tool'
      path: '/api/public/connector/setup-tool'
      fullPath: '/api/public/connector/setup-tool'
      preLoaderRoute: typeof ApiPublicConnectorSetupToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/result': {
      id: '/api/public/connector/result'
      path: '/api/public/connector/result'
      fullPath: '/api/public/connector/result'
      preLoaderRoute: typeof ApiPublicConnectorResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/pair': {
      id: '/api/public/connector/pair'
      path: '/api/public/connector/pair'
      fullPath: '/api/public/connector/pair'
      preLoaderRoute: typeof ApiPublicConnectorPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/jobs': {
      id: '/api/public/connector/jobs'
      path: '/api/public/connector/jobs'
      fullPath: '/api/public/connector/jobs'
      preLoaderRoute: typeof ApiPublicConnectorJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/heartbeat': {
      id: '/api/public/connector/heartbeat'
      path: '/api/public/connector/heartbeat'
      fullPath: '/api/public/connector/heartbeat'
      preLoaderRoute: typeof ApiPublicConnectorHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/download': {
      id: '/api/public/connector/download'
      path: '/api/public/connector/download'
      fullPath: '/api/public/connector/download'
      preLoaderRoute: typeof ApiPublicConnectorDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/devices': {
      id: '/api/public/connector/devices'
      path: '/api/public/connector/devices'
      fullPath: '/api/public/connector/devices'
      preLoaderRoute: typeof ApiPublicConnectorDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/test-lab/sandbox': {
      id: '/_authenticated/app/test-lab/sandbox'
      path: '/sandbox'
      fullPath: '/app/test-lab/sandbox'
      preLoaderRoute: typeof AuthenticatedAppTestLabSandboxRouteImport
      parentRoute: typeof AuthenticatedAppTestLabRoute
    }
    '/_authenticated/app/test-lab/real': {
      id: '/_authenticated/app/test-lab/real'
      path: '/real'
      fullPath: '/app/test-lab/real'
      preLoaderRoute: typeof AuthenticatedAppTestLabRealRouteImport
      parentRoute: typeof AuthenticatedAppTestLabRoute
    }
    '/_authenticated/app/test-lab/mcp': {
      id: '/_authenticated/app/test-lab/mcp'
      path: '/mcp'
      fullPath: '/app/test-lab/mcp'
      preLoaderRoute: typeof AuthenticatedAppTestLabMcpRouteImport
      parentRoute: typeof AuthenticatedAppTestLabRoute
    }
    '/_authenticated/app/easy/vouchers': {
      id: '/_authenticated/app/easy/vouchers'
      path: '/vouchers'
      fullPath: '/app/easy/vouchers'
      preLoaderRoute: typeof AuthenticatedAppEasyVouchersRouteImport
      parentRoute: typeof AuthenticatedAppEasyRoute
    }
    '/_authenticated/app/easy/$screen': {
      id: '/_authenticated/app/easy/$screen'
      path: '/$screen'
      fullPath: '/app/easy/$screen'
      preLoaderRoute: typeof AuthenticatedAppEasyScreenRouteImport
      parentRoute: typeof AuthenticatedAppEasyRoute
    }
    '/api/public/hooks/telegram/callback': {
      id: '/api/public/hooks/telegram/callback'
      path: '/api/public/hooks/telegram/callback'
      fullPath: '/api/public/hooks/telegram/callback'
      preLoaderRoute: typeof ApiPublicHooksTelegramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/syslog/$token': {
      id: '/api/public/hooks/syslog/$token'
      path: '/api/public/hooks/syslog/$token'
      fullPath: '/api/public/hooks/syslog/$token'
      preLoaderRoute: typeof ApiPublicHooksSyslogTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/install/windows': {
      id: '/api/public/connector/install/windows'
      path: '/api/public/connector/install/windows'
      fullPath: '/api/public/connector/install/windows'
      preLoaderRoute: typeof ApiPublicConnectorInstallWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/install/macos': {
      id: '/api/public/connector/install/macos'
      path: '/api/public/connector/install/macos'
      fullPath: '/api/public/connector/install/macos'
      preLoaderRoute: typeof ApiPublicConnectorInstallMacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connector/install/linux': {
      id: '/api/public/connector/install/linux'
      path: '/api/public/connector/install/linux'
      fullPath: '/api/public/connector/install/linux'
      preLoaderRoute: typeof ApiPublicConnectorInstallLinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppEasyRouteChildren {
  AuthenticatedAppEasyScreenRoute: typeof AuthenticatedAppEasyScreenRoute
  AuthenticatedAppEasyVouchersRoute: typeof AuthenticatedAppEasyVouchersRoute
}

const AuthenticatedAppEasyRouteChildren: AuthenticatedAppEasyRouteChildren = {
  AuthenticatedAppEasyScreenRoute: AuthenticatedAppEasyScreenRoute,
  AuthenticatedAppEasyVouchersRoute: AuthenticatedAppEasyVouchersRoute,
}

const AuthenticatedAppEasyRouteWithChildren =
  AuthenticatedAppEasyRoute._addFileChildren(AuthenticatedAppEasyRouteChildren)

interface AuthenticatedAppTestLabRouteChildren {
  AuthenticatedAppTestLabMcpRoute: typeof AuthenticatedAppTestLabMcpRoute
  AuthenticatedAppTestLabRealRoute: typeof AuthenticatedAppTestLabRealRoute
  AuthenticatedAppTestLabSandboxRoute: typeof AuthenticatedAppTestLabSandboxRoute
  AuthenticatedAppTestLabIndexRoute: typeof AuthenticatedAppTestLabIndexRoute
}

const AuthenticatedAppTestLabRouteChildren: AuthenticatedAppTestLabRouteChildren =
  {
    AuthenticatedAppTestLabMcpRoute: AuthenticatedAppTestLabMcpRoute,
    AuthenticatedAppTestLabRealRoute: AuthenticatedAppTestLabRealRoute,
    AuthenticatedAppTestLabSandboxRoute: AuthenticatedAppTestLabSandboxRoute,
    AuthenticatedAppTestLabIndexRoute: AuthenticatedAppTestLabIndexRoute,
  }

const AuthenticatedAppTestLabRouteWithChildren =
  AuthenticatedAppTestLabRoute._addFileChildren(
    AuthenticatedAppTestLabRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccessPointsRoute: typeof AuthenticatedAppAccessPointsRoute
  AuthenticatedAppAgentRoute: typeof AuthenticatedAppAgentRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppBackupsRoute: typeof AuthenticatedAppBackupsRoute
  AuthenticatedAppConnectorsRoute: typeof AuthenticatedAppConnectorsRoute
  AuthenticatedAppDeploymentsRoute: typeof AuthenticatedAppDeploymentsRoute
  AuthenticatedAppDevicesRoute: typeof AuthenticatedAppDevicesRoute
  AuthenticatedAppEasyRoute: typeof AuthenticatedAppEasyRouteWithChildren
  AuthenticatedAppFleetRoute: typeof AuthenticatedAppFleetRoute
  AuthenticatedAppI18nRoute: typeof AuthenticatedAppI18nRoute
  AuthenticatedAppIncidentsRoute: typeof AuthenticatedAppIncidentsRoute
  AuthenticatedAppLiveRoute: typeof AuthenticatedAppLiveRoute
  AuthenticatedAppMagicDudeRoute: typeof AuthenticatedAppMagicDudeRoute
  AuthenticatedAppManualRoute: typeof AuthenticatedAppManualRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppOwnerOperationsRoute: typeof AuthenticatedAppOwnerOperationsRoute
  AuthenticatedAppPortalRoute: typeof AuthenticatedAppPortalRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppQuickSetupRoute: typeof AuthenticatedAppQuickSetupRoute
  AuthenticatedAppReadinessRoute: typeof AuthenticatedAppReadinessRoute
  AuthenticatedAppResellerOperationRoute: typeof AuthenticatedAppResellerOperationRoute
  AuthenticatedAppRevenueRoute: typeof AuthenticatedAppRevenueRoute
  AuthenticatedAppRoutersRoute: typeof AuthenticatedAppRoutersRoute
  AuthenticatedAppScriptsRoute: typeof AuthenticatedAppScriptsRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSitesRoute: typeof AuthenticatedAppSitesRoute
  AuthenticatedAppSyslogRoute: typeof AuthenticatedAppSyslogRoute
  AuthenticatedAppTenantsRoute: typeof AuthenticatedAppTenantsRoute
  AuthenticatedAppTerminalRoute: typeof AuthenticatedAppTerminalRoute
  AuthenticatedAppTestLabRoute: typeof AuthenticatedAppTestLabRouteWithChildren
  AuthenticatedAppTopologyRoute: typeof AuthenticatedAppTopologyRoute
  AuthenticatedAppUsageRoute: typeof AuthenticatedAppUsageRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppVoucherLayoutsRoute: typeof AuthenticatedAppVoucherLayoutsRoute
  AuthenticatedAppVouchersRoute: typeof AuthenticatedAppVouchersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccessPointsRoute: AuthenticatedAppAccessPointsRoute,
  AuthenticatedAppAgentRoute: AuthenticatedAppAgentRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppBackupsRoute: AuthenticatedAppBackupsRoute,
  AuthenticatedAppConnectorsRoute: AuthenticatedAppConnectorsRoute,
  AuthenticatedAppDeploymentsRoute: AuthenticatedAppDeploymentsRoute,
  AuthenticatedAppDevicesRoute: AuthenticatedAppDevicesRoute,
  AuthenticatedAppEasyRoute: AuthenticatedAppEasyRouteWithChildren,
  AuthenticatedAppFleetRoute: AuthenticatedAppFleetRoute,
  AuthenticatedAppI18nRoute: AuthenticatedAppI18nRoute,
  AuthenticatedAppIncidentsRoute: AuthenticatedAppIncidentsRoute,
  AuthenticatedAppLiveRoute: AuthenticatedAppLiveRoute,
  AuthenticatedAppMagicDudeRoute: AuthenticatedAppMagicDudeRoute,
  AuthenticatedAppManualRoute: AuthenticatedAppManualRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppOwnerOperationsRoute: AuthenticatedAppOwnerOperationsRoute,
  AuthenticatedAppPortalRoute: AuthenticatedAppPortalRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppQuickSetupRoute: AuthenticatedAppQuickSetupRoute,
  AuthenticatedAppReadinessRoute: AuthenticatedAppReadinessRoute,
  AuthenticatedAppResellerOperationRoute:
    AuthenticatedAppResellerOperationRoute,
  AuthenticatedAppRevenueRoute: AuthenticatedAppRevenueRoute,
  AuthenticatedAppRoutersRoute: AuthenticatedAppRoutersRoute,
  AuthenticatedAppScriptsRoute: AuthenticatedAppScriptsRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSitesRoute: AuthenticatedAppSitesRoute,
  AuthenticatedAppSyslogRoute: AuthenticatedAppSyslogRoute,
  AuthenticatedAppTenantsRoute: AuthenticatedAppTenantsRoute,
  AuthenticatedAppTerminalRoute: AuthenticatedAppTerminalRoute,
  AuthenticatedAppTestLabRoute: AuthenticatedAppTestLabRouteWithChildren,
  AuthenticatedAppTopologyRoute: AuthenticatedAppTopologyRoute,
  AuthenticatedAppUsageRoute: AuthenticatedAppUsageRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppVoucherLayoutsRoute: AuthenticatedAppVoucherLayoutsRoute,
  AuthenticatedAppVouchersRoute: AuthenticatedAppVouchersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DevHomeThumbsRoute: DevHomeThumbsRoute,
  DevQuickConfigIconsRoute: DevQuickConfigIconsRoute,
  DevSitesMapRoute: DevSitesMapRoute,
  DevUxShellRoute: DevUxShellRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicConnectorDevicesRoute: ApiPublicConnectorDevicesRoute,
  ApiPublicConnectorDownloadRoute: ApiPublicConnectorDownloadRoute,
  ApiPublicConnectorHeartbeatRoute: ApiPublicConnectorHeartbeatRoute,
  ApiPublicConnectorJobsRoute: ApiPublicConnectorJobsRoute,
  ApiPublicConnectorPairRoute: ApiPublicConnectorPairRoute,
  ApiPublicConnectorResultRoute: ApiPublicConnectorResultRoute,
  ApiPublicConnectorSetupToolRoute: ApiPublicConnectorSetupToolRoute,
  ApiPublicConnectorVersionRoute: ApiPublicConnectorVersionRoute,
  ApiPublicHooksDbBackupRoute: ApiPublicHooksDbBackupRoute,
  ApiPublicHooksFleetAiScanRoute: ApiPublicHooksFleetAiScanRoute,
  ApiPublicHooksVoucherMaintenanceRoute: ApiPublicHooksVoucherMaintenanceRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  ApiPublicConnectorInstallLinuxRoute: ApiPublicConnectorInstallLinuxRoute,
  ApiPublicConnectorInstallMacosRoute: ApiPublicConnectorInstallMacosRoute,
  ApiPublicConnectorInstallWindowsRoute: ApiPublicConnectorInstallWindowsRoute,
  ApiPublicHooksSyslogTokenRoute: ApiPublicHooksSyslogTokenRoute,
  ApiPublicHooksTelegramCallbackRoute: ApiPublicHooksTelegramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
