// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import {
  clearSessionExpired,
  isUnauthorizedSessionError,
  notifySessionExpired,
} from "@/lib/session-events";

let refreshPromise: ReturnType<typeof supabase.auth.refreshSession> | null = null;

function refreshSessionOnce() {
  if (!refreshPromise) {
    refreshPromise = supabase.auth.refreshSession().finally(() => {
      refreshPromise = null;
    });
  }
  return refreshPromise;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let session = data.session;
    const expiresSoon =
      session?.expires_at != null && session.expires_at <= Math.floor(Date.now() / 1000) + 60;

    if (session && expiresSoon) {
      const refreshed = await refreshSessionOnce();
      if (refreshed.error || !refreshed.data.session) {
        notifySessionExpired();
        // Do not invoke a protected server function without a bearer token.
        // Public functions still pass through when there was no session at
        // all, but an invalidated authenticated session must stop here.
        throw new Error("Unauthorized: Session expired");
      } else {
        session = refreshed.data.session;
        clearSessionExpired();
      }
    }

    try {
      return await next({
        headers: session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {},
      });
    } catch (error) {
      if (isUnauthorizedSessionError(error)) notifySessionExpired();
      throw error;
    }
  },
);
